portraits =
{
	{'MAN1', 1},
	{'MAN2', 1},
	{'GENDWRF', 1},
	{'GENMELF', 1},
	{'GENMHLF', 1},
	--{'NHORC', 1},
	{'AJANTIS', 1},
	{'CORAN', 1},
	{'EDWIN', 1},
	{'ELDOTH', 1},
	{'GARRICK', 1},
	{'KAGAIN', 1},
	{'KHALID', 1},
	{'KIVAN', 1},
	{'MINSC', 1},
	{'MONTAR', 1},
	{'QUAYLE', 1},
	{'TIAX', 1},
	{'XAN', 1},
	{'XZAR', 1},
	{'YESLICK', 1},
	{'RASAAD', 1},
	{'DORN',	1},
	--{'BAELOTH',	1},
	--{'NCERND', 1},
	--{'NKELDOR', 1},
	--{'NANOMEN', 1},
	--{'NEDWIN', 1},
	--{'NHAER', 1},
	--{'NJAN', 1},
	--{'NMINSC', 1},
	--{'NVALYGA', 1},
	--{'NYOSHIM', 1},
	--{'NKORGAN', 1},
	{'MANLEY0', 1},
	{'MANLEY3', 1},
	{'MANLEY6', 1},
	{'MANLEY7', 1},
	{'MANLEY8', 1},
	{'MANLEY9', 1},
	{'BDSHAM1', 1},
	{'BDORCM1', 1},
	{'HELM', 1},
	{'HVLN', 1},
	{'WOMAN1', 2},
	{'WOMAN2', 2},
	{'ALORA', 2},
	{'BRANWE', 2},
	{'DYNAHEI', 2},
	{'FALDORN', 2},
	{'IMOEN', 2},
	{'JAHEIRA', 2},
	{'SAFANA', 2},
	{'SHARTEL', 2},
	{'SKIE', 2},
	{'VICONIA', 2},
	{'NEERA', 2},
	--{'NNALIA', 2},
	--{'NMAZZY', 2},
	--{'NAERIE', 2},
	--{'NJAHEIR', 2},
	--{'NVICON', 2},
	{'MANLEY1', 2},
	{'MANLEY2', 2},
	{'MANLEY4', 2},
	{'MANLEY5', 2},
	{'MANLEYX', 2},
	{'BDSHAF1', 2},
	{'BDORCF1', 2},
	{'SKAN', 2}
}

movies = 
{
	{'intro', 1, 120, 32207, 0, 1},
	{'intro', 719, 779, 32166, 1, 1},
	{'intro', 809, 869, 32167, 0, 1},
	{'intro', 889, 959, 32168, 0, 1},
	{'intro', 949, 989, 32169, 1, 1},
	{'blackpit', 0, 89, 32170, 1, 1},
	{'blackpit', 119, 299, 32171, 1, 1},
	{'blackpit', 329, 389, 32172, 1, 1},
	{'blackpit', 449, 599, 32173, 1, 1},
	{'blackpit', 629, 719, 32174, 1, 1}
}
credits =
{
	24632,
	24633,
	24684,
	24685,
	24686,
	24687,
	32283,
	24701,	-- French Translation Team
	24702,	-- Spanish Translation Team
	24721,	-- German Translation Team
	24727,	-- Portuguese Brazilian Translation Team
	24705,	-- Polish Translation Team
	24713,  -- Italian Translation Team
	24707,	-- Czech Translation Team
	24719,	-- Turkish Translation Team
	24717,	-- Korean Translation Team
	24715,	-- Japanese Translation Team
	24709,	-- Chinese Simplified Team
	24688,	-- Original Interplay Bioware Credits
	24689,
	24690,
	24691,
	24692,
	24693,
	24694,
	24695,
	24696,
	24697,
}

mageBookStrings = {
	SPWI908 = {tip = 24615, title = 'CHAIN_CONTINGENCY_TITLE', action = "ADD_SPELLS_CONTINGENCY_LABEL"},
	SPWI617 = {tip = 24615, title = 'CONTINGENCY_TITLE', action = "ADD_SPELLS_CONTINGENCY_LABEL"},
	SPWI809 = {tip = 24617, title = 'SPELL_TRIGGER_TITLE', action = "ADD_SPELLS_TRIGGER_LABEL"},
	SPWI710 = {tip = 24616, title = 'SPELL_SEQUENCER_TITLE', action = "ADD_SPELLS_SEQUENCER_LABEL"},
	SPWI420 = {tip = 24616, title = 'MINOR_SEQUENCER_TITLE', action = "ADD_SPELLS_SEQUENCER_LABEL"},
	}

Infinity_AddDLC( 'dorn', 'DLCDN', 31092, 31093, 'BGEE_IOS_DORN', 0, 'baldursgate_android_dorn' )
Infinity_AddDLC( 'neera', 'DLCNE', 31090, 31091, 'BGEE_IOS_NEERA', 0, 'baldursgate_android_neera' )
Infinity_AddDLC( 'manley', 'DLCP1', 31094, 31095, 'BGEE_IOS_PORTRAITPACK1', 0, 'baldursgate_android_portraitpack1' )
Infinity_AddDLC( 'voice', 'DLCV1', 31096, 31097, 'BGEE_IOS_VOICEPACK1', 0, 'baldursgate_android_voicepack1' )

Infinity_AddDLCContent('FEMALE4', 4 )
Infinity_AddDLCContent('FEMALE5', 4 )
Infinity_AddDLCContent('FEMALE6', 4 )
Infinity_AddDLCContent('MALE4', 4 )
Infinity_AddDLCContent('MALE5', 4 )
Infinity_AddDLCContent('MALE6', 4 )
Infinity_AddDLCContent('DORN', 1 )
Infinity_AddDLCContent('NEERA', 2 )
Infinity_AddDLCContent('MANLEY0', 3 )
Infinity_AddDLCContent('MANLEY1', 3 )
Infinity_AddDLCContent('MANLEY2', 3 )
Infinity_AddDLCContent('MANLEY3', 3 )
Infinity_AddDLCContent('MANLEY4', 3 )
Infinity_AddDLCContent('MANLEY5', 3 )
Infinity_AddDLCContent('MANLEY6', 3 )
Infinity_AddDLCContent('MANLEY7', 3 )
Infinity_AddDLCContent('MANLEY8', 3 )
Infinity_AddDLCContent('MANLEY9', 3 )
Infinity_AddDLCContent('MANLEYX', 3 )

keybindings = 
{
	{
		{ 1,	1,	'Inventory',				"ASSIGN_KEYS_PAGE_INVENTORY",				'',		0,	105 },
		{ 2,	1,	'Character Record',			"ASSIGN_KEYS_PAGE_CHARACTERINFORMATION",	'',		0,	114 },
		{ 3,	1,	'Return To Game',			"ASSIGN_KEYS_PAGE_RETURNTOGAME",			'',		0,	103 },
		{ 4,	1,	'Journal',					"ASSIGN_KEYS_PAGE_JOURNAL",					'',		0,	106 },
		{ 5,	1,	'Map',						"ASSIGN_KEYS_PAGE_AREAMAP",					'',		0,	109 },
		{ 6,	1,	'Wizard Spells',			"ASSIGN_KEYS_PAGE_MAGESPELLS",				'',		0,	119 },
		{ 7,	1,	'Priest Spells',			"ASSIGN_KEYS_PAGE_PRIESTSPELLS",			'',		0,	112 },
		{ 8,	1,	'Options',					"ASSIGN_KEYS_PAGE_OPTIONS",					'',		0,	111 },
		{ 9,	1,	'Character Arbitration',	"ASSIGN_KEYS_PAGE_CHARACTERARBITRATION",	'',		0,	99 }
	},
	{
		{ 10,	2,	'Guard / Protect',			"ASSIGN_KEYS_ACTIONS_GUARD",				'',		0,	0 },
		{ 11,	2,	'Turn Undead',				"ASSIGN_KEYS_ACTIONS_TURNUNDEAD",			'',		0,	0 },
		{ 12, 2,	'Battle Song',				"ASSIGN_KEYS_ACTIONS_BARDSONG",				'',		0,	0 },
		{ 13, 2,	'Cast Spell',				"ASSIGN_KEYS_ACTIONS_CASTSPELL",			'',		0,	0 },
		{ 14, 2,	'Use Item',					"ASSIGN_KEYS_ACTIONS_USEITEM",				'',		0,	0 },
		{ 15, 2,	'Dialog',					"ASSIGN_KEYS_ACTIONS_DIALOG",				'',		0,	0 },
		{ 16, 2,	'Thieving',					"ASSIGN_KEYS_ACTIONS_THIEVING",				'',		0,	0 },
		{ 17, 2,	'Stealth',					"ASSIGN_KEYS_ACTIONS_STEALTH",				'',		0,	0 },
		{ 18, 2,	'Trap Detection',			"ASSIGN_KEYS_ACTIONS_FINDTRAPS",			'',		0,	0 },
		{ 19, 2,	'Group Stop',				"ASSIGN_KEYS_ACTIONS_GROUPSTOP",			'',		0,	0 },
		{ 20, 2,	'Group Attack',				"ASSIGN_KEYS_ACTIONS_GROUPATTACK",			'',		0,	0 },
		{ 21, 2,	'Special Abilities',		"ASSIGN_KEYS_ACTIONS_SPECIALABILITIES",		'',		0,	0 },
		{ 22, 2,	'Equip Melee Weapon',		"ASSIGN_KEYS_ACTIONS_EQUIPMELEEWEAPON",		'',		0,	0 },
		{ 23, 2,	'Equip Range Weapon',		"ASSIGN_KEYS_ACTIONS_EQUIPRANGEDWEAPON",	'',		0,	0 }
	},
	{
		{ 24, 3,	'Quick Load',				"ASSIGN_KEYS_MISC_QUICKLOAD",		'',		0,	108 },
		{ 25, 3,	'Hide Interface',			"ASSIGN_KEYS_MISC_HIDEINTERFACE",	'',		0,	104 },
		{ 26, 3,	'Right Interface',			"ASSIGN_KEYS_MISC_RIGHTINTERFACE",	'',		0,	117 },
		{ 27, 3,	'Chat Window',				"ASSIGN_KEYS_MISC_CHATWINDOW",		'',		0,	116 },
		{ 28, 3,	'Location',					"ASSIGN_KEYS_MISC_LOCATION",		'',		0,	120 },
		{ 29, 3,	'Quick Save',				"ASSIGN_KEYS_MISC_QUICKSAVE",		'',		0,	113 },
		{ 30, 3,	'Toggle AI',				"ASSIGN_KEYS_MISC_TOGGLEAI",		'',		0,	97 },
		{ 31, 3,	'Left Interface',			"ASSIGN_KEYS_MISC_LEFTINTERFACE",	'',		0,	121 },
		{ 32, 3,	'Rest',						"ASSIGN_KEYS_MISC_REST",			'',		0,	0 },
		{ 33, 3,	'Hard Pause',				"ASSIGN_KEYS_MISC_HARDPAUSE",		'',		0,	0 },
		{ 34, 3,   'Scroll Up',					"ASSIGN_KEYS_MISC_SCROLLUP",		'',		0,	0 },
		{ 35, 3,   'Scroll Right',				"ASSIGN_KEYS_MISC_SCROLLRIGHT",		'',		0,	0 },
		{ 36, 3,   'Scroll Down',				"ASSIGN_KEYS_MISC_SCROLLDOWN",		'',		0,	0 },
		{ 37, 3,   'Scroll Left',				"ASSIGN_KEYS_MISC_SCROLLLEFT",		'',		0,	0 },
		{ 38, 3, 'Zoom In',						"ASSIGN_KEYS_QUICKSLOTS_ZOOMIN",  	'',		0,	61 },
		{ 39, 3, 'Zoom Out',					"ASSIGN_KEYS_QUICKSLOTS_ZOOMOUT",  	'',		0,	45 },
		{ 40, 3, 'Quick Loot',					"32217",							'',		0,	0 }
	},
	{
		{ 41,	4,	'Spell Slot 1',				"ASSIGN_KEYS_QUICKSLOTS_SPELLSLOT1",		'',		0,	0 },
		{ 42,	4,	'Spell Slot 2',				"ASSIGN_KEYS_QUICKSLOTS_SPELLSLOT2",		'',		0,	0 },
		{ 43,	4,	'Spell Slot 3',				"ASSIGN_KEYS_QUICKSLOTS_SPELLSLOT3",		'',		0,	0 },
		{ 44,	4,	'Weapon Slot 1',			"ASSIGN_KEYS_QUICKSLOTS_WEAPONSLOT1",		'',		0,	0 },
		{ 45,	4,	'Weapon Slot 2',			"ASSIGN_KEYS_QUICKSLOTS_WEAPONSLOT2",		'',		0,	0 },
		{ 46,	4,	'Weapon Slot 3',			"ASSIGN_KEYS_QUICKSLOTS_WEAPONSLOT3",		'',		0,	0 },
		{ 47,	4,	'Weapon Slot 4',			"ASSIGN_KEYS_QUICKSLOTS_WEAPONSLOT4",		'',		0,	0 },
		{ 48,	4,	'Item Slot 1',				"ASSIGN_KEYS_QUICKSLOTS_ITEMSLOT1",			'',		0,	0 },
		{ 49,	4,	'Item Slot 2',				"ASSIGN_KEYS_QUICKSLOTS_ITEMSLOT2",			'',		0,	0 },
		{ 50,	4,	'Item Slot 3',				"ASSIGN_KEYS_QUICKSLOTS_ITEMSLOT3",			'',		0,	0 },
		{ 51,	4,	'Formation Slot 1',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT1",	'',		0,	0 },
		{ 52,	4,	'Formation Slot 2',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT2",	'',		0,	0 },
		{ 53,	4,	'Formation Slot 3',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT3",	'',		0,	0 },
		{ 54,	4,	'Formation Slot 4',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT4",	'',		0,	0 },
		{ 55,	4,	'Formation Slot 5',			"ASSIGN_KEYS_QUICKSLOTS_FORMATIONSLOT5",	'',		0,	0 },
		{ 56, 4, 'Character 1',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER1",  		'',		0,	49 },
		{ 57, 4, 'Character 2',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER2",  		'',		0,	50 },
		{ 58, 4, 'Character 3',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER3",  		'',		0,	51 },
		{ 59, 4, 'Character 4',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER4",  		'',		0,	52 },
		{ 60, 4, 'Character 5',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER5",  		'',		0,	53 },
		{ 61, 4, 'Character 6',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTER6",  		'',		0,	54 },
		{ 62, 4, 'Characters 1&2',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS12",  	'',		0,	55 },
		{ 63, 4, 'Characters 3&4',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS34",  	'',		0,	56 },
		{ 64, 4, 'Characters 5&6',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS56",  	'',		0,	57 },
		{ 65, 4, 'Select 1,2,3',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS123",  	'',		0,	0 },
		{ 66, 4, 'Select 4,5,6',				"ASSIGN_KEYS_QUICKSLOTS_CHARACTERS456",  	'',		0,	0 },
		{ 67, 4, 'Select all',					"ASSIGN_KEYS_QUICKSLOTS_SELECTALL",  		'',		0,	48 }
	},
	{
		{ 189, 5,  'SPPR101',					26122,  '',     0,	0 }, -- Bless
		{ 190, 5,  'SPPR102',					26125,  '',		0,	0 }, -- Command
		{ 191, 5,  'SPPR103',					25886,  '',		0,	0 }, -- Cure Light Wounds
		{ 192, 5,  'SPPR104',					25811,  '',		0,	0 }, -- Detect Evil
		{ 193, 5,  'SPPR105',					26127,	'',		0,	0 }, -- Entangle
		{ 194, 5,  'SPPR106',					26129,  '',     0,	0 }, -- Magical Stone
		{ 195, 5,  'SPPR107',					25813,  '',     0,	0 }, -- Protection From Evil
		{ 196, 5,  'SPPR108',					25816,  '',     0,	0 }, -- Remove Fear
		{ 197, 5,  'SPPR109',					26132,  '',		0,	0 }, -- Sanctuary
		{ 198, 5,  'SPPR110',					26134,	'',		0,	0 }, -- Shillelagh
		{ 199, 5, 'SPPR111',					26136, '',		0,	0 }, -- Armor of Faith
		{ 200, 5, 'SPPR113',					26138, '',		0,	0 }, -- Doom
		{ 201, 5, 'SPPR150',					32348, '',		0,	0 }, -- Spirit Ward
		{ 202, 5,  'SPPR201',					26141,  '',     0,	0 }, -- Aid
		{ 203, 5,  'SPPR202',					26144,  '',		0,	0 }, -- Barkskin
		{ 204, 5,  'SPPR203',					26146,	'',		0,	0 }, -- Chant
		{ 205, 5,  'SPPR204',					12910,	'',		0,	0 }, -- Charm Person or Mammal
		{ 206, 5,  'SPPR205',					26149,	'',		0,	0 }, -- Find Traps
		{ 207, 5,	'SPPR206',					25922,	'',		0,	0 }, -- Flame Blade
		{ 208, 5,	'SPPR207',					26151,	'',		0,	0 }, -- Goodberry
		{ 209,	5,	'SPPR208',					26106,	'',		0,	0 }, -- Hold Person
		{ 210,	5,	'SPPR209',					26154,	'',		0,	0 }, -- Know Alignment
		{ 211,	5,	'SPPR210',					26157,	'',		0,	0 }, -- Resist Fire and Cold
		{ 212,	5,	'SPPR211',					25951,	'',		0,	0 }, -- Silence, 15' Radius
		{ 213,	5,	'SPPR212',					25887,	'',		0,	0 }, -- Slow Poison
		{ 214,	5,	'SPPR213',					25900,	'',		0,	0 }, -- Spiritual Hammer
		{ 215,	5,	'SPPR214',					25889,	'',		0,	0 }, -- Draw Upon Holy Might
		{ 216,  5,  'SPPR250',					32350, '',		0,	0 }, -- Writhing Fog
		{ 217,	5,	'SPPR301',					26161,	'',		0,	0 }, -- Animate Dead
		{ 218,	5,	'SPPR302',					26163,	'',		0,	0 }, -- Call Lightning
		{ 219,	5,	'SPPR303',					25819,	'',		0,	0 }, -- Dispel Magic
		{ 220,	5,	'SPPR304',					26165,	'',		0,	0 }, -- Glyph of Warding
		{ 221,	5,	'SPPR305',					26167,	'',		0,	0 }, -- Hold Animal
		{ 223,	5,	'SPPR306',					26169,	'',		0,	0 }, -- Protection From Fire
		{ 224,	5,	'SPPR307',					26172,	'',		0,	0 }, -- Remove Curse
		{ 225,	5,	'SPPR308',					26175,	'',		0,	0 }, -- Remove Paralysis
		{ 226, 5,	'SPPR309',					26177,	'',		0,	0 }, -- Invisibility Purge
		{ 227,	5,	'SPPR310',					26180,	'',		0,	0 }, -- Miscast Magic
		{ 228,	5,	'SPPR311',					26182,	'',		0,	0 }, -- Rigid Thinking
		{ 229,	5,	'SPPR312',					26185,	'',		0,	0 }, -- Strength of One
		{ 230, 5, 'SPPR313',					26187, '',		0,	0 }, -- Holy Smite
		{ 231, 5, 'SPPR314',					26189, '',		0,	0 }, -- Unholy Blight
		{ 232, 5, 'SPPR315',					26191, '',		0,	0 }, -- Cure Medium Wounds
		{ 233, 5, 'SPPR317',					26193, '',		0,	0 }, -- Cure Disease
		{ 234, 5, 'SPPR318',					26196, '',		0,	0 }, -- Zone of Sweet Air
		{ 235, 5, 'SPPR319',					25948, '',		0,	0 }, -- Summon Insects
		{ 236, 5, 'SPPR350',					32352, '',		0,	0 }, -- Spiritual Clarity
		{ 237,	5,	'SPPR401',					26092,	'',		0,	0 }, -- Cure Serious Wounds
		{ 238,	5,	'SPPR402',					26199,	'',		0,	0 }, -- Animal Summoning I
		{ 239,	5,	'SPPR403',					26200,	'',		0,	0 }, -- Free Action
		{ 240,	5,	'SPPR404',					26202,	'',		0,	0 }, -- Neutralize Poison
		{ 241,	5,	'SPPR405',					26204,	'',		0,	0 }, -- Mental Domination
		{ 242, 5,	'SPPR406',					26207,	'',		0,	0 }, -- Defensive Harmony
		{ 243,	5,	'SPPR407',					26209,	'',		0,	0 }, -- Protection From Lightning
		{ 244,	5,	'SPPR408',					25824,	'',		0,	0 }, -- Protection From Evil, 10' Radius
		{ 245, 5, 'SPPR409',					26211, '',		0,	0 }, -- Death Ward
		{ 246, 5, 'SPPR410',					26213, '',		0,	0 }, -- Call Woodland Beings
		{ 247, 5, 'SPPR411',					26215, '',		0,	0 }, -- Poison
		{ 248, 5, 'SPPR412',					26217, '',		0,	0 }, -- Holy Power
		{ 249, 5, 'SPPR413',					26219, '',		0,	0 }, -- Negative Plane Protection
		{ 250, 5, 'SPPR414',					26104, '',		0,	0 }, -- Cause Serious Wounds
		{ 251, 5, 'SPPR415',					26222, '',		0,	0 }, -- Farsight
		{ 252, 5, 'SPPR416',					26224, '',		0,	0 }, -- Cloak of Fear
		{ 253, 5, 'SPPR417',					26226, '',		0,	0 }, -- Lesser Restoration
		{ 254, 5, 'SPPR450',					32354, '',		0,	0 }, -- Spirit Fire
		{ 255,	5,	'SPPR501',					26228,	'',		0,	0 }, -- Animal Summoning II
		{ 256,	5,	'SPPR502',					26230,	'',		0,	0 }, -- Cure Critical Wounds
		{ 257,	5,	'SPPR503',					26004,	'',		0,	0 }, -- Flame Strike
		{ 258,	5,	'SPPR504',					26232,	'',		0,	0 }, -- Raise Dead
		{ 259,	5,	'SPPR505',					25822,	'',		0,	0 }, -- True Seeing
		{ 260,	5,	'SPPR506',					26234,	'',		0,	0 }, -- Iron Skins
		{ 261, 5, 'SPPR507',					26236, '',		0,	0 }, -- Champion's Strength
		{ 262,	5,	'SPPR508',					26238,	'',		0,	0 }, -- Chaotic Commands		
		{ 263, 5, 'SPPR509',					26241, '',		0,	0 }, -- Magic Resistance
		{ 264, 5, 'SPPR510',					26243, '',		0,	0 }, -- Cause Critical Wounds
		{ 265, 5, 'SPPR511',					26245, '',		0,	0 }, -- Slay Living
		{ 266, 5, 'SPPR512',					26247, '',		0,	0 }, -- Greater Command
		{ 267, 5, 'SPPR513',					26249, '',		0,	0 }, -- Righteous Magic
		{ 268, 5, 'SPPR514',					26251, '',		0,	0 }, -- Mass Cure
		{ 269, 5, 'SPPR515',					26253, '',		0,	0 }, -- Repulse Undead
		{ 270, 5, 'SPPR516',					26255, '',		0,	0 }, -- Pixie Dust
		{ 271, 5, 'SPPR517',					26257, '',		0,	0 }, -- Insect Plague
		{ 272, 5, 'SPPR550',					32356, '',		0,	0 }, -- Recall Spirit
		{ 273, 5, 'SPPR601',					26259, '',		0,	0 }, -- Aerial Servant
		{ 274, 5, 'SPPR602',					26261, '',		0,	0 }, -- Animal Summoning III
		{ 275, 5, 'SPPR603',					26263, '',		0,	0 }, -- Blade Barrier
		{ 276, 5, 'SPPR604',					26265, '',		0,	0 }, -- Conjure Animals
		{ 277, 5, 'SPPR605',					26267, '',		0,	0 }, -- Conjure Fire Elemental
		{ 278, 5, 'SPPR606',					26269, '',		0,	0 }, -- Fire Seeds
		{ 279, 5, 'SPPR607',					25931, '',		0,	0 }, -- Heal
		{ 280, 5, 'SPPR608',					26272, '',		0,	0 }, -- Harm
		{ 281, 5, 'SPPR609',					26274, '',		0,	0 }, -- False Dawn
		{ 282, 5, 'SPPR610',					26276, '',		0,	0 }, -- Dolorous Decay
		{ 283, 5, 'SPPR611',					26278, '',		0,	0 }, -- Wondrous Recall
		{ 284, 5, 'SPPR612',					26280, '',		0,	0 }, -- Bolt of Glory
		{ 285, 5, 'SPPR613',					26282, '',		0,	0 }, -- Physical Mirror
		{ 286, 5, 'SPPR614',					26284, '',		0,	0 }, -- Sol's Searing Orb
		{ 287, 5, 'SPPR650',					32358, '',		0,	0 }, -- Spiritual Lock
		{ 288, 5, 'SPPR701',					26286, '',		0,	0 }, -- Shield of the Archons
		{ 289, 5, 'SPPR702',					26289, '',		0,	0 }, -- Conjure Earth Elemental
		{ 290, 5, 'SPPR703',					26291, '',		0,	0 }, -- Gate
		{ 291, 5, 'SPPR704',					26293, '',		0,	0 }, -- Nature's Beauty
		{ 292, 5, 'SPPR705',					26296, '',		0,	0 }, -- Fire Storm
		{ 293, 5, 'SPPR706',					26298, '',		0,	0 }, -- Symbol, Fear
		{ 294, 5, 'SPPR707',					26300, '',		0,	0 }, -- Sunray
		{ 295, 5, 'SPPR708',					26095, '',		0,	0 }, -- Finger of Death
		{ 296, 5, 'SPPR709',					25968, '',		0,	0 }, -- Confusion
		{ 297, 5, 'SPPR710',					26303, '',		0,	0 }, -- Holy Word
		{ 298, 5, 'SPPR711',					26305, '',		0,	0 }, -- Regeneration
		{ 299, 5, 'SPPR712',					26308, '',		0,	0 }, -- Resurrection
		{ 300, 5, 'SPPR713',					26310, '',		0,	0 }, -- Greater Restoration
		{ 301, 5, 'SPPR715',					26312, '',		0,	0 }, -- Unholy Word
		{ 302, 5, 'SPPR717',					26314, '',		0,	0 }, -- Creeping Doom
		{ 303, 5, 'SPPR718',					26315, '',		0,	0 }, -- Symbol, Stun
		{ 304, 5, 'SPPR719',					26317, '',		0,	0 }, -- Symbol, Death
		{ 305, 5, 'SPPR720',					26319, '',		0,	0 }, -- Earthquake
		{ 306, 5, 'SPPR721',					26321, '',		0,	0 }, -- Energy Blades
		{ 307, 5, 'SPPR729',					26324, '',		0,	0 }, -- Mass Raise Dead
		{ 308, 5, 'SPPR750',					32360, '',		0,	0 }, -- Ether Gate
		{ 309, 5, 'SPPR751',					32362, '',		0,	0 } -- Ethereal Retribution
	},
	{
		{ 310,  6, 'SPWI101',					26344,	'',		0,	0 }, -- Grease
		{ 311,  6, 'SPWI102',					26346,	'',		0,	0 }, -- Armor
		{ 312, 6, 'SPWI103',					26349,	'',		0,	0 }, -- Burning Hands
		{ 313, 6, 'SPWI104',					13015,	'',		0,	0 }, -- Charm Person
		{ 314, 6, 'SPWI105',					26071,	'',		0,	0 }, -- Color Spray
		{ 315, 6, 'SPWI106',					26352,	'',		0,	0 }, -- Blindness
		{ 316, 6, 'SPWI107',					26354,	'',		0,	0 }, -- Friends
		{ 317, 6, 'SPWI108',					26357,	'',		0,	0 }, -- Protection From Petrification
		{ 318, 6, 'SPWI110',					26360,	'',		0,	0 }, -- Identify
		{ 319, 6, 'SPWI111',					26362,	'',		0,	0 }, -- Infravision
		{ 320, 6, 'SPWI112',					12052,	'',		0,	0 }, -- Magic Missile
		{ 321, 6, 'SPWI113',					12023,	'',		0,	0 }, -- Protection From Evil
		{ 322, 6, 'SPWI114',					26366,	'',		0,	0 }, -- Shield
		{ 323, 6, 'SPWI115',					26369,	'',		0,	0 }, -- Shocking Grasp
		{ 324, 6, 'SPWI116',					26040,	'',		0,	0 }, -- Sleep
		{ 325, 6, 'SPWI117',					26372,	'',		0,	0 }, -- Chill Touch
		{ 326, 6, 'SPWI118',					12054,	'',		0,	0 }, -- Chromatic Orb
		{ 327, 6, 'SPWI119',					25892,	'',		0,	0 }, -- Larloch's Minor Drain
		{ 328, 6, 'SPWI120',					26374,	'',		0,	0 }, -- Reflected Image
		{ 329, 6, 'SPWI123',					25831,	'',		0,	0 }, -- Find Familiar
		{ 330, 6, 'SPWI124',					26377,	'',		0,	0 }, -- Nahal's Reckless Dweomer
		{ 331, 6, 'SPWI125',					26379,	'',		0,	0 }, -- Spook
		{ 332, 6, 'SPWI201',					26077,	'',		0,	0 }, -- Blur
		{ 333, 6, 'SPWI202',					25811,	'',		0,	0 }, -- Detect Evil
		{ 334, 6, 'SPWI203',					26382,	'',		0,	0 }, -- Detect Invisibility
		{ 335, 6, 'SPWI205',					25894,	'',		0,	0 }, -- Horror
		{ 336, 6, 'SPWI206',					25906,	'',		0,	0 }, -- Invisibility
		{ 337, 6, 'SPWI207',					26384,	'',		0,	0 }, -- Knock
		{ 338, 6, 'SPWI208',					26154,	'',		0,	0 }, -- Know Alignment
		{ 339, 6, 'SPWI209',					26388,	'',		0,	0 }, -- Luck
		{ 340, 6, 'SPWI210',					26391,	'',		0,	0 }, -- Resist Fear
		{ 341, 6, 'SPWI211',					26393,	'',		0,	0 }, -- Melf's Acid Arrow
		{ 342, 6, 'SPWI212',					25959,	'',		0,	0 }, -- Mirror Image
		{ 343, 6, 'SPWI213',					26074,	'',		0,	0 }, -- Stinking Cloud
		{ 344, 6, 'SPWI214',					26014,	'',		0,	0 }, -- Strength
		{ 345, 6, 'SPWI215',					25864,	'',		0,	0 }, -- Web
		{ 346, 6, 'SPWI217',					26105,	'',		0,	0 }, -- Agannazar's Scorcher
		{ 347, 6, 'SPWI218',					26398,	'',		0,	0 }, -- Ghoul Touch
		{ 348, 6, 'SPWI219',					26400,	'',		0,	0 }, -- Vocalize
		{ 349, 6, 'SPWI220',					26403,	'',		0,	0 }, -- Power Word, Sleep
		{ 350, 6, 'SPWI221',					26405,	'',		0,	0 }, -- Ray of Enfeeblement
		{ 351, 6, 'SPWI222',					31239,	'',		0,	0 }, -- Chaos Shield
		{ 352, 6, 'SPWI223',					26408,	'',		0,	0 }, -- Deafness
		{ 353, 6, 'SPWI224',					26410,	'',		0,	0 }, -- Glitterdust
		{ 354, 6, 'SPWI301',					26415,	'',		0,	0 }, -- Clairvoyance
		{ 355, 6, 'SPWI302',					26417,	'',		0,	0 }, -- Remove Magic
		{ 356, 6, 'SPWI303',					26418,	'',		0,	0 }, -- Flame Arrow
		{ 357, 6, 'SPWI304',					25963,	'',		0,	0 }, -- Fireball
		{ 358, 6, 'SPWI305',					26018,	'',		0,	0 }, -- Haste
		{ 359, 6, 'SPWI306',					26106,	'',		0,	0 }, -- Hold Person
		{ 360, 6, 'SPWI307',					26421,	'',		0,	0 }, -- Invisibility, 10' Radius
		{ 361, 6, 'SPWI308',					25852,	'',		0,	0 }, -- Lightning Bolt
		{ 362, 6, 'SPWI309',					26336,	'',		0,	0 }, -- Monster Summoning I
		{ 363, 6, 'SPWI310',					26423,	'',		0,	0 }, -- Non-Detection
		{ 364, 6, 'SPWI311',					26333,	'',		0,	0 }, -- Protection From Normal Missiles
		{ 365, 6, 'SPWI312',					26103,	'',     0,	0 }, -- Slow
		{ 366, 6, 'SPWI313',					26426,	'',		0,	0 }, -- Skull Trap
		{ 367, 6, 'SPWI314',					25896,	'',		0,	0 }, -- Vampiric Touch
		{ 368, 6, 'SPWI315',					12020,	'',		0,	0 }, -- Wraithform
		{ 369, 6, 'SPWI316',					17392,	'',		0,	0 }, -- Dire Charm
		{ 370, 6, 'SPWI317',					26429,	'',		0,	0 }, -- Ghost Armor
		{ 371, 6, 'SPWI318',					26330,	'',		0,	0 }, -- Minor Spell Deflection
		{ 372, 6, 'SPWI319',					26169,	'',		0,	0 }, -- Protection From Fire
		{ 373, 6, 'SPWI320',					26432,	'',		0,	0 }, -- Protection From Cold
		{ 374, 6, 'SPWI321',					26435,	'',		0,	0 }, -- Spell Thrust
		{ 375, 6, 'SPWI322',					26438,	'',		0,	0 }, -- Detect Illusion
		{ 376, 6, 'SPWI324',					25855,	'',		0,	0 }, -- Hold Undead
		{ 377, 6, 'SPWI325',					26441,	'',		0,	0 }, -- Melf's Minute Meteors
		{ 378, 6, 'SPWI326',					25819,	'',		0,	0 }, -- Dispel Magic
		{ 379, 6, 'SPWI401',					25968,	'',		0,	0 }, -- Confusion
		{ 380, 6, 'SPWI402',					26445,	'',		0,	0 }, -- Dimension Door
		{ 381, 6, 'SPWI403',					25700,	'',		0,	0 }, -- Fire Shield (Blue)
		{ 382, 6, 'SPWI404',					26447,	'',		0,	0 }, -- Ice Storm
		{ 383, 6, 'SPWI405',					25868,	'',		0,	0 }, -- Improved Invisibility
		{ 384, 6, 'SPWI406',					26448,	'',		0,	0 }, -- Minor Globe of Invulnerability
		{ 385, 6, 'SPWI407',					26339,	'',		0,	0 }, -- Monster Summoning II
		{ 386, 6, 'SPWI408',					25954,	'',		0,	0 }, -- Stoneskin
		{ 387, 6, 'SPWI409',					26451,	'',		0,	0 }, -- Contagion
		{ 388, 6, 'SPWI410',					26172,	'',		0,	0 }, -- Remove Curse
		{ 389, 6, 'SPWI411',					26455,	'',		0,	0 }, -- Emotion: Hopelessness
		{ 390, 6, 'SPWI412',					26457,	'',		0,	0 }, -- Greater Malison
		{ 391, 6, 'SPWI413',					26027,	'',		0,	0 }, -- Otiluke's Resilient Sphere
		{ 392, 6, 'SPWI414',					26459,	'',		0,	0 }, -- Spirit Armor
		{ 393, 6, 'SPWI415',					20963,	'',		0,	0 }, -- Polymorph Other
		{ 394, 6, 'SPWI416',					26461,	'',		0,	0 }, -- Polymorph Self
		{ 395, 6, 'SPWI417',					26465,	'',		0,	0 }, -- Enchanted Weapon
		{ 396, 6, 'SPWI418',					26326,	'',		0,	0 }, -- Fire Shield (Red)
		{ 397, 6, 'SPWI419',					26467,	'',		0,	0 }, -- Secret Word
		{ 398, 6, 'SPWI420',					26469,	'',		0,	0 }, -- Minor Sequencer
		{ 399, 6, 'SPWI421',					26473,	'',		0,	0 }, -- Teleport Field
		{ 400, 6, 'SPWI423',					26475,	'',		0,	0 }, -- Spider Spawn
		{ 401, 6, 'SPWI424',					26222,	'',		0,	0 }, -- Farsight
		{ 402, 6, 'SPWI425',					26477,	'',		0,	0 }, -- Wizard Eye
		{ 403, 6, 'SPWI501',					26489,	'',		0,	0 }, -- Animate Dead
		{ 404, 6, 'SPWI502',					25927,	'',		0,	0 }, -- Cloudkill
		{ 405, 6, 'SPWI503',					26492,	'',		0,	0 }, -- Cone of Cold
		{ 406, 6, 'SPWI504',					26494,	'',		0,	0 }, -- Monster Summoning III
		{ 407, 6, 'SPWI505',					26496,	'',		0,	0 }, -- Shadow Door
		{ 408, 6, 'SPWI506',					26035,	'',		0,	0 }, -- Domination
		{ 409, 6, 'SPWI507',					26499,	'',		0,	0 }, -- Hold Monster
		{ 410, 6, 'SPWI508',					25871,	'',		0,	0 }, -- Chaos
		{ 411, 6, 'SPWI509',					26501,	'',		0,	0 }, -- Feeblemind
		{ 412, 6, 'SPWI510',					26503,	'',		0,	0 }, -- Spell Immunity
		{ 413, 6, 'SPWI511',					26505,	'',		0,	0 }, -- Protection From Normal Weapons
		{ 414, 6, 'SPWI512',					26510,	'',		0,	0 }, -- Protection From Electricity
		{ 415, 6, 'SPWI513',					26513,	'',		0,	0 }, -- Breach
		{ 416, 6, 'SPWI514',					26084,	'',		0,	0 }, -- Lower Resistance
		{ 417, 6, 'SPWI515',					26528,	'',		0,	0 }, -- Oracle
		{ 418, 6, 'SPWI516',					26530,	'',		0,	0 }, -- Conjure Lesser Fire Elemental
		{ 419, 6, 'SPWI517',					26532,	'',		0,	0 }, -- Protection From Acid
		{ 420, 6, 'SPWI518',					26535,	'',		0,	0 }, -- Phantom Blade
		{ 421, 6, 'SPWI519',					26537,	'',		0,	0 }, -- Spell Shield
		{ 422, 6, 'SPWI520',					26540,	'',		0,	0 }, -- Conjure Lesser Air Elemental
		{ 423, 6, 'SPWI521',					26542,	'',		0,	0 }, -- Conjure Lesser Earth Elemental
		{ 424, 6, 'SPWI522',					26058,	'',		0,	0 }, -- Minor Spell Turning
		{ 425, 6, 'SPWI523',					26546,	'',		0,	0 }, -- Sunfire
		{ 426, 6, 'SPWI601',					26556,	'',		0,	0 }, -- Invisible Stalker
		{ 427, 6, 'SPWI602',					26558,	'',		0,	0 }, -- Globe of Invulnerability
		{ 428, 6, 'SPWI603',					26560,	'',		0,	0 }, -- Tenser's Transformation
		{ 429, 6, 'SPWI604',					26030,	'',		0,	0 }, -- Flesh to Stone
		{ 430, 6, 'SPWI605',					26562,	'',		0,	0 }, -- Death Spell
		{ 431, 6, 'SPWI606',					26564,	'',		0,	0 }, -- Protection From Magic Energy
		{ 432, 6, 'SPWI607',					26567,	'',		0,	0 }, -- Mislead
		{ 433, 6, 'SPWI608',					26570,	'',		0,	0 }, -- Pierce Magic
		{ 434, 6, 'SPWI609',					25821,	'',		0,	0 }, -- True Sight
		{ 435, 6, 'SPWI611',					25942,	'',		0,	0 }, -- Protection From Magical Weapons
		{ 436, 6, 'SPWI612',					26342,	'',		0,	0 }, -- Power Word, Silence
		{ 437, 6, 'SPWI613',					26573,	'',		0,	0 }, -- Improved Haste
		{ 438, 6, 'SPWI614',					26575,	'',		0,	0 }, -- Death Fog
		{ 439, 6, 'SPWI615',					25797,	'',		0,	0 }, -- Chain Lightning
		{ 440, 6, 'SPWI616',					26102,	'',		0,	0 }, -- Disintegrate
		{ 441, 6, 'SPWI617',					26577,	'',		0,	0 }, -- Contingency
		{ 442, 6, 'SPWI618',					25970,	'',		0,	0 }, -- Spell Deflection
		{ 443, 6, 'SPWI619',					26579,	'',		0,	0 }, -- Wyvern Call
		{ 444, 6, 'SPWI620',					26267,	'',		0,	0 }, -- Conjure Fire Elemental
		{ 445, 6, 'SPWI621',					26582,	'',		0,	0 }, -- Conjure Air Elemental
		{ 446, 6, 'SPWI622',					26289,	'',		0,	0 }, -- Conjure Earth Elemental
		{ 447, 6, 'SPWI623',					26585,	'',		0,	0 }, -- Carrion Summons
		{ 448, 6, 'SPWI624',					26587,	'',		0,	0 }, -- Summon Nishruu
		{ 449, 6, 'SPWI625',					26589,	'',		0,	0 }, -- Stone to Flesh
		{ 450, 6, 'SPWI701',					26591,	'',		0,	0 }, -- Spell Turning
		{ 451, 6, 'SPWI702',					26594,	'',		0,	0 }, -- Protection From The Elements
		{ 452, 6, 'SPWI703',					25720,	'',		0,	0 }, -- Project Image
		{ 453, 6, 'SPWI704',					26086,	'',		0,	0 }, -- Ruby Ray of Reversal
		{ 454, 6, 'SPWI705',					26599,	'',		0,	0 }, -- Khelben's Warding Whip
		{ 455, 6, 'SPWI707',					26601,	'',		0,	0 }, -- Cacofiend
		{ 456, 6, 'SPWI708',					26603,	'',		0,	0 }, -- Mantle
		{ 457, 6, 'SPWI710',					26606,	'',		0,	0 }, -- Spell Sequencer
		{ 458, 6, 'SPWI711',					26607,	'',		0,	0 }, -- Sphere of Chaos
		{ 459, 6, 'SPWI712',					26609,	'',		0,	0 }, -- Delayed Blast Fireball
		{ 460, 6, 'SPWI713',					26095,	'',		0,	0 }, -- Finger of Death
		{ 461, 6, 'SPWI714',					26611,	'',		0,	0 }, -- Prismatic Spray
		{ 462, 6, 'SPWI715',					26079,	'',		0,	0 }, -- Power Word, Stun
		{ 463, 6, 'SPWI716',					26613,	'',		0,	0 }, -- Mordenkainen's Sword
		{ 464, 6, 'SPWI717',					26615,	'',		0,	0 }, -- Summon Efreeti
		{ 465, 6, 'SPWI718',					26617,	'',		0,	0 }, -- Summon Djinni
		{ 466, 6, 'SPWI719',					26619,	'',		0,	0 }, -- Summon Hakeashar
		{ 467, 6, 'SPWI720',					26621,	'',		0,	0 }, -- Control Undead
		{ 468, 6, 'SPWI721',					26623,	'',		0,	0 }, -- Mass Invisibility
		{ 469, 6, 'SPWI722',					26625,	'',		0,	0 }, -- Limited Wish
		{ 470, 6, 'SPWI723',					31242,	'',		0,	0 }, -- Improved Chaos Shield
		{ 471, 6, 'SPWI803',					26627,	'',		0,	0 }, -- Protection From Energy
		{ 472, 6, 'SPWI804',					26630,	'',		0,	0 }, -- Simulacrum
		{ 473, 6, 'SPWI805',					26633,	'',		0,	0 }, -- Pierce Shield
		{ 474, 6, 'SPWI807',					26635,	'',		0,	0 }, -- Summon Fiend
		{ 475, 6, 'SPWI808',					26637,	'',		0,	0 }, -- Improved Mantle
		{ 476, 6, 'SPWI809',					26640,	'',		0,	0 }, -- Spell Trigger
		{ 477, 6, 'SPWI810',					26642,	'',		0,	0 }, -- Incendiary Cloud
		{ 478, 6, 'SPWI811',					26298,	'',		0,	0 }, -- Symbol, Fear
		{ 479, 6, 'SPWI812',					26645,	'',		0,	0 }, -- Abi-Dalzim's Horrid Wilting
		{ 480, 6, 'SPWI813',					25993,	'',		0,	0 }, -- Maze
		{ 481, 6, 'SPWI815',					26647,	'',		0,	0 }, -- Power Word, Blind
		{ 482, 6, 'SPWI816',					26315,	'',		0,	0 }, -- Symbol, Stun
		{ 483, 6, 'SPWI817',					26317,	'',		0,	0 }, -- Symbol, Death
		{ 484, 6, 'SPWI818',					26651,	'',		0,	0 }, -- Bigby's Clenched Fist
		{ 485, 6, 'SPWI902',					26653,	'',		0,	0 }, -- Spell Trap
		{ 486, 6, 'SPWI903',					26656,	'',		0,	0 }, -- Spellstrike
		{ 487, 6, 'SPWI905',					26291,	'',		0,	0 }, -- Gate
		{ 488, 6, 'SPWI907',					26659,	'',		0,	0 }, -- Absolute Immunity
		{ 489, 6, 'SPWI908',					26662,	'',		0,	0 }, -- Chain Contingency
		{ 490, 6, 'SPWI909',					26664,	'',		0,	0 }, -- Time Stop
		{ 491, 6, 'SPWI910',					26002,	'',		0,	0 }, -- Imprisonment
		{ 492, 6, 'SPWI911',					25976,	'',		0,	0 }, -- Meteor Swarm
		{ 493, 6, 'SPWI912',					26087,	'',		0,	0 }, -- Power Word, Kill
		{ 494, 6, 'SPWI913',					25934,	'',		0,	0 }, -- Wail of the Banshee
		{ 495, 6, 'SPWI914',					26666,	'',		0,	0 }, -- Energy Drain 
		{ 496, 6, 'SPWI915',					26668,	'',		0,	0 }, -- Black Blade of Disaster
		{ 497, 6, 'SPWI916',					26670,	'',		0,	0 }, -- Shapechange
		{ 498, 6, 'SPWI917',					26673,	'',		0,	0 }, -- Freedom
		{ 499, 6, 'SPWI918',					26675,	'',		0,	0 }, -- Bigby's Crushing Hand
		{ 500, 6, 'SPWI919',					26677,	'',		0,	0 } -- Wish		
	}
};
keycategories = 
{
	{ 1, "ASSIGN_KEYS_PAGE", 			'Keymap Page' },
	{ 2, "ASSIGN_KEYS_ACTIONS", 		'Keymap Action' },
	{ 3, "ASSIGN_KEYS_MISC", 			'Keymap Miscellaneous' },
	{ 4, "ASSIGN_KEYS_QUICKSLOTS", 		'Keymap Quick Slots' },
	{ 5, "ASSIGN_KEYS_PRIESTSPELLS",	'Priest Spells' },
	{ 6, "ASSIGN_KEYS_MAGESPELLS", 		'Mage Spells' }
};

languages = {
	{'zh_CN', 24709, 24710, 'Chinese'},
	{'cs_CZ', 24707, 24708, 'Czech'},
	{'en_US', 24698, 24699, 'English'},
	{'fr_FR', 24701, 24704, 'French'},
	{'de_DE', 24721, 24722, 'German'},
	{'hu_HU', 32335, 32336, 'Hungarian'},
	{'it_IT', 24713, 24714, 'Italian'},
	{'ja_JP', 24715, 24716, 'Japanese'},
	{'ko_KR', 24717, 24718, 'Korean'},
	{'pl_PL', 24705, 24706, 'Polish'},
	{'pt_BR', 24727, 24728, 'Portuguese'},
	{'ru_RU', 24723, 24724, 'Russian'},
	{'es_ES', 24702, 24703, 'Spanish'},
	{'tr_TR', 24719, 24720, 'Turkish'},
	{'uk_UA', 24725, 24726, 'Ukrainian'}
}

journal={}
info={}
user={}

mp_sessions = {}
mp_sessions_jid = {}
mp_backend_type = 0
passwordMp = "password"

font_colors={}
--not from bgee. doesn't seem to be used in dragonspear:
-- font_colors['REALMS'] 	= '0xFFE2DDCF'
-- font_colors['NORMAL']	= '0xFF2C2121'
-- font_colors['STONESML']	= '0xFFCECECE'
-- font_colors['STONEBIG']	= '0xFFBCBCBC'
-- font_colors['INITIALS']	= '0xFFB98C00'

--from IWDEE, doesn't seem to be filled in for dragonspear
filenames_stringrefs={}
-- filenames_stringrefs['MALE1'] = {12345, 2}
-- filenames_stringrefs['FEMALE1'] = {40380, 2}
-- filenames_stringrefs['FEMALE2'] = {40381, 2}
-- filenames_stringrefs['FEMALE3'] = {40382, 2}
-- filenames_stringrefs['FFIGHT1'] = {40375, 2}
-- filenames_stringrefs['FFIGHT2'] = {40376, 2}
-- filenames_stringrefs['FFIGHT3'] = {40377, 2}
-- filenames_stringrefs['FFIGHT4'] = {40378, 2}
-- filenames_stringrefs['FFIGHT5'] = {40379, 2}
-- filenames_stringrefs['FMAGE1'] = {40383, 2}
-- filenames_stringrefs['FMAGE2'] = {40384, 2}
-- filenames_stringrefs['FMAGE3'] = {40385, 2}
-- filenames_stringrefs['FMAGE4'] = {40386, 2}
-- filenames_stringrefs['FMAGE5'] = {40387, 2}
-- filenames_stringrefs['FTHIEF1'] = {40388, 2}
-- filenames_stringrefs['FTHIEF2'] = {40389, 2}
-- filenames_stringrefs['MALE1'] = {40390, 2}
-- filenames_stringrefs['MALE2'] = {40391, 2}
-- filenames_stringrefs['MALE3'] = {40392, 2}
-- filenames_stringrefs['MFIGHT1'] = {40393, 2}
-- filenames_stringrefs['MFIGHT2'] = {40394, 2}
-- filenames_stringrefs['MFIGHT3'] = {40395, 2}
-- filenames_stringrefs['MFIGHT4'] = {40396, 2}
-- filenames_stringrefs['MFIGHT5'] = {40397, 2}
-- filenames_stringrefs['MMAGE1'] = {40398, 2}
-- filenames_stringrefs['MMAGE2'] = {40399, 2}
-- filenames_stringrefs['MMAGE3'] = {40400, 2}
-- filenames_stringrefs['MMAGE4'] = {40401, 2}
-- filenames_stringrefs['MMAGE5'] = {40402, 2}
-- filenames_stringrefs['MTHIEF1'] = {40403, 2}
-- filenames_stringrefs['MTHIEF2'] = {40404, 2}

messageBoxMessageCount = 7
--TODO these should really become string refs.
-- CLOUD_SAVE_DOWNLOAD_FAILED,
-- CLOUD_SAVE_METADATA_WRITE_FAILED,
-- CLOUD_SAVE_METADATA_READ_FAILED,
-- CLOUD_SAVE_SNAPSHOT_LIST_DOWNLOAD_FAILED,
-- CLOUD_SAVE_CLOUD_READ_FAILED
-- CLOUD_SAVE_QUOTA_EXCEEDED
-- CLOUD_SAVE_FILE_TOO_LARGE	
messages = 
{
	'An error occurred while downloading a cloud save.',
	'An error occurred while writing a cloud save metadata file.',
	'An error occurred while reading a cloud save metadata file.',
	'An error occurred while downloading the list of cloud save files.',
	'An error occurred while uploading a cloud save.',
	'Your Steam cloud save storage quota has been exceeded.',
	'Save file is too large to upload to the Steam cloud.'
}

textflashes = {}
textflashidx = 1

cheatAreas = {
	{"AR0002", "Temple of Helm (Baldur's Gate)"},
	{"AR0004", "Behren's home, ground floor"},
	{"AR0005", "Behren's home, second floor (Pixie the Cat)"},
	{"AR0006", "Rinnie's home, ground floor"},
	{"AR0007", "Rinnie's home, second floor"},
	{"AR0008", "Generic home, ground floor"},
	{"AR0009", "Generic home, second floor"},
	{"AR0010", "Jardak's home, ground floor (Drelik the butler)"},
	{"AR0011", "Jardak's home, second floor"},
	{"AR0012", "Generic home, ground floor"},
	{"AR0013", "Generic home, second floor"},
	{"AR0014", "Generic home, ground floor"},
	{"AR0015", "Generic home, second floor"},
	{"AR0016", "Generic home, ground floor"},
	{"AR0017", "Generic home, second floor"},
	{"AR0018", "Generic home, ground floor"},
	{"AR0019", "Generic home, second floor"},
	{"AR0020", "Generic home, ground floor"},
	{"AR0021", "Generic home, second floor"},
	{"AR0100", "NW Baldur's Gate (Helm & Cloak, Silvershield Estate)"},
	{"AR0101", "Silvershield Estate, ground floor"},
	{"AR0102", "Silvershield Estate, second floor"},
	{"AR0103", "Splurging Sturgeon, ground floor (Lusselyn)"},
	{"AR0104", "Splurging Sturgeon, second floor (Mr. Shade)"},
	{"AR0105", "Blade and Stars, ground floor (G'axir the Seer, Elkart)"},
	{"AR0106", "Blade and Stars, second floor (Maple Willow Aspen)"},
	{"AR0107", "Blade and stars, third floor (Reginald Longtooth Worthington III)"},
	{"AR0108", "Duchal Palace, ground floor"},
	{"AR0109", "Duchal Palace, second floor"},
	{"AR0110", "Duchal Palace, third floor"},
	{"AR0111", "Duchal Palace, basement"},
	{"AR0112", "Undercellars (Slythe, Krystin)"},
	{"AR0114", "Blushing Mermaid, ground floor (Larze)"},
	{"AR0115", "Blushing Mermaid, second floor"},
	{"AR0116", "Helm & Cloak, ground floor (Gorpel Hind)"},
	{"AR0117", "Helm & Cloak, second floor front (Emissary Sarah)"},
	{"AR0118", "Helm & Cloak, second floor rear"},
	{"AR0119", "Three Old Kegs tavern, ground floor"},
	{"AR0120", "Three Old Kegs tavern, second floor (Skull of Keraph)"},
	{"AR0121", "Three Old Kegs tavern, third floor (Areana)"},
	{"AR0123", "Undercity (Temple of Bhaal, old city ruins)"},
	{"AR0125", "Temple of Bhaal (game finale)"},
	{"AR0126", "Ragefast's home"},
	{"AR0127", "Merchant League, ground floor (Irlentree)"},
	{"AR0128", "Merchant League, second floor (Aldeth, Brandilar, Zorl)"},
	{"AR0129", "Merchant League, third floor"},
	{"AR0130", "Hall of Wonders (Alora)"},
	{"AR0131", "Temple of Gond (Forthel August)"},
	{"AR0132", "Lady's House (Agnasia, Chanthalas Ulbright)"},
	{"AR0133", "Low Lantern, ground floor"},
	{"AR0134", "Low Lantern, first underwater level (Desreta, Vay-ya)"},
	{"AR0135", "Low Lantern, second underwater level (Yago)"},
	{"AR0136", "Low Lantern, third underwater level"},
	{"AR0137", "Ramazith's Tower, ground floor"},
	{"AR0138", "Ramazith's Tower, sixth (top) floor"},
	{"AR0139", "Ramazith's Tower, second floor"},
	{"AR0140", "Ramazith's Tower, third floor"},
	{"AR0141", "Ramazith's Tower, fourth floor"},
	{"AR0142", "Ramazith's Tower, fifth floor"},
	{"AR0143", "Oberan's Estate, ground floor"},
	{"AR0144", "Oberan's Estate, second floor"},
	{"AR0145", "Oberan's Estate, third floor (Helshara, Ithmeera, Delorna)"},
	{"AR0146", "Thieves Guild, Maze"},
	{"AR0148", "Thieves Guild, front house (fourth from west)"},
	{"AR0149", "Ilmater's Shrine"},
	{"AR0150", "Thieves Guild, front house (first from west)"},
	{"AR0151", "Thieves Guild, front house (second from west)"},
	{"AR0152", "Thieves Guild, front house (third from west)"},
	{"AR0153", "Thieves Guild, main area (Alatos, Narlen Darkwalk)"},
	{"AR0154", "Keexie Tavern, ground floor"},
	{"AR0155", "Generic home, ground floor"},
	{"AR0156", "Generic home, second floor"},
	{"AR0157", "Quinn's home, ground floor"},
	{"AR0158", "Quinn's home, second floor"},
	{"AR0159", "Generic home, ground floor"},
	{"AR0160", "Generic home, second floor"},
	{"AR0161", "Degrodel's home"},
	{"AR0162", "Louise and Laerta's home"},
	{"AR0163", "Generic home, ground floor"},
	{"AR0164", "Generic home, second floor"},
	{"AR0165", "Generic tavern, ground floor (Connoly Finn)"},
	{"AR0166", "Generic tavern, second floor (Borinole Mann)"},
	{"AR0167", "Phierkas's home, ground floor"},
	{"AR0168", "Phierkas's home, second floor"},
	{"AR0169", "Generic home, ground floor"},
	{"AR0170", "Generic home, second floor"},
	{"AR0171", "Keexie Tavern, second floor"},
	{"AR0200", "N Baldur's Gate (Ramazith's Tower, Duchal Palace)"},
	{"AR0224", "BG Sewers, western area (Schlumpsha the Sewer King)"},
	{"AR0225", "BG Sewers, central area (Ratchild)"},
	{"AR0226", "BG Sewers, eastern area (ogre mage for Scar)"},
	{"AR0300", "NE Baldur's Gate (Blushing Mermaid, Splurging Sturgeon, Counting House)"},
	{"AR0302", "Generic home, ground floor"},
	{"AR0303", "Generic home, second floor"},
	{"AR0304", "Generic store"},
	{"AR0305", "Generic home, ground floor"},
	{"AR0306", "Generic home, second floor"},
	{"AR0307", "Counting House, ground floor (Jacil or Ulf)"},
	{"AR0308", "Counting House, second floor (Captain Kieres)"},
	{"AR0400", "Farm NE of BG (Wenric, zombie farm)"},
	{"AR0401", "Wenric's farmhouse"},
	{"AR0500", "Durlag's Tower, exterior"},
	{"AR0501", "Durlag's Tower, first subterranean level"},
	{"AR0502", "Durlag's Tower, ground floor"},
	{"AR0503", "Durlag's Tower, second floor"},
	{"AR0504", "Durlag's Tower, third floor (Rigglio)"},
	{"AR0505", "Durlag's Tower, fourth floor (Kirinhale)"},
	{"AR0506", "Durlag's Tower, chessboard (fourth subterranean level)"},
	{"AR0507", "Durlag's Tower, cold elemental challenge (fourth subterranean level)"},
	{"AR0508", "Durlag's Tower, fire elemental challenge (fourth subterranean level)"},
	{"AR0509", "Durlag's Tower, air elemental challenge (fourth subterranean level)"},
	{"AR0510", "Durlag's Tower, earth elemental challenge (fourth subterranean level)"},
	{"AR0511", "Durlag's Tower, second subterranean level (Pride, Avarice, Love, Fear)"},
	{"AR0512", "Durlag's Tower, third subterranean level (Kiel, Islanne, door maze)"},
	{"AR0513", "Durlag's Tower, fourth subterranean level (leads to elemental challenges)"},
	{"AR0514", "Durlag's Tower, fifth subterranean level"},
	{"AR0515", "Durlag's Tower, stone golem question chamber"},
	{"AR0516", "Durlag's Tower, demon knight chamber (Dalton)"},
	{"AR0600", "W Baldur's Gate (Hall of Wonders, Lady's House, Ragefast's home)"},
	{"AR0601", "Seven Suns, ground floor"},
	{"AR0602", "Seven Suns, second floor"},
	{"AR0603", "Seven Suns, basement (Jhasso)"},
	{"AR0606", "Flaming Fist HQ, basement"},
	{"AR0607", "Flaming Fist HQ, ground floor"},
	{"AR0608", "Flaming Fist HQ, second floor (Duke Eltan)"},
	{"AR0609", "Temple of Umberlee (Jalantha Mistmyr)"},
	{"AR0611", "Iron Throne, basement"},
	{"AR0612", "Iron Throne, second floor (Dra'tan)"},
	{"AR0613", "Iron Throne, third floor (Nortuary, Emissary Tar)"},
	{"AR0614", "Iron Throne, fourth floor (Destus Gurn)"},
	{"AR0615", "Iron Throne, fifth (top) floor (chapter five finale)"},
	{"AR0616", "Iron Throne, ground floor (Triadore)"},
	{"AR0617", "Tremain Belde'ar's home, ground floor"},
	{"AR0618", "Tremain Belde'ar's home, second floor"},
	{"AR0619", "Fenten's Home, ground floor"},
	{"AR0620", "Fenten's Home, second floor"},
	{"AR0621", "Iron Throne, roof"},
	{"AR0700", "Central Baldur's Gate (marketplace, Oberan's home)"},
	{"AR0702", "Harbormaster's building"},
	{"AR0703", "Sorcerous Sundries, ground floor (Halbazzer Drin)"},
	{"AR0704", "Sorcerous Sundries, second floor"},
	{"AR0705", "Elfsong Tavern, ground floor (Brevlik)"},
	{"AR0706", "Elfsong Tavern, second floor (Alyth, Cyrdemac)"},
	{"AR0707", "Generic home, ground floor"},
	{"AR0708", "Generic home, second floor"},
	{"AR0709", "Generic home, ground floor"},
	{"AR0710", "Generic home, second floor"},
	{"AR0711", "Generic home, ground floor"},
	{"AR0712", "Generic home, second floor"},
	{"AR0713", "Generic home, ground floor"},
	{"AR0714", "Generic home, second floor"},
	{"AR0715", "Nadine's home, ground floor"},
	{"AR0716", "Nadine's home, second floor"},
	{"AR0717", "Generic home, ground floor"},
	{"AR0718", "Generic home, second floor"},
	{"AR0719", "Felonius Gist's home"},
	{"AR0720", "Drakon Tavern"},
	{"AR0721", "Warehouse full of rabid chickens"},
	{"AR0722", "Generic home, ground floor"},
	{"AR0723", "Generic home, second floor"},
	{"AR0724", "Marketplace tent (gambling)"},
	{"AR0725", "Marketplace tent (gambling)"},
	{"AR0726", "Diviner's marketplace tent"},
	{"AR0800", "E Baldur's Gate (Sorcerous Sundries, Elfsong Tavern)"},
	{"AR0801", "Generic home, ground floor"},
	{"AR0802", "Generic home, second floor"},
	{"AR0803", "Maltz's Weapon Shop, ground floor"},
	{"AR0804", "Maltz's Weapon Shop, second floor"},
	{"AR0805", "Arkion's home, ground floor"},
	{"AR0806", "Arkion's home, second floor"},
	{"AR0807", "Generic inn, ground floor"},
	{"AR0808", "Generic inn, second floor"},
	{"AR0809", "Silence's store"},
	{"AR0810", "Luck Aello's store"},
	{"AR0811", "Generic home, ground floor"},
	{"AR0812", "Generic home, second floor"},
	{"AR0813", "Nemphre's home, ground floor"},
	{"AR0814", "Nemphre's home, second floor"},
	{"AR0900", "Wyrm's Crossing (bridge to BG, Tenya, Quayle)"},
	{"AR0901", "Tenya's home"},
	{"AR1000", "Ulgoth's Beard (Shandalar, Ike, Mendas)"},
	{"AR1001", "Ulgoth Beard's Inn (Hurgan Stoneblade)"},
	{"AR1002", "Aec'Letec cult building, basement (Aec'Letec)"},
	{"AR1003", "Aec'Letec cult building, ground floor"},
	{"AR1004", "Mendas's home"},
	{"AR1005", "Therella's home"},
	{"AR1006", "Generic home"},
	{"AR1007", "Generic home"},
	{"AR1008", "Ice island, exterior"},
	{"AR1009", "Ice island, dungeon"},
	{"AR1010", "Ice island, unused exit area"},
	{"AR1100", "SW Baldur's Gate (Flaming Fist HQ, Merchant League, Seven Suns)"},
	{"AR1101", "Generic home, ground floor (thieves Wiven, Dirk, Meakin and Sath)"},
	{"AR1102", "Generic home, second floor"},
	{"AR1103", "Generic home, ground floor"},
	{"AR1104", "Generic home, second floor"},
	{"AR1105", "Generic home, ground floor"},
	{"AR1106", "Generic home, second floor"},
	{"AR1107", "Generic home, ground floor"},
	{"AR1108", "Generic home, second floor"},
	{"AR1109", "Generic tavern, ground floor (Phandalyn)"},
	{"AR1110", "Generic tavern, second floor"},
	{"AR1111", "Sunin's home"},
	{"AR1112", "Generic weapons store"},
	{"AR1113", "Ye Olde Inn, ground floor (green slimes, AKA Slime Inn)"},
	{"AR1114", "Ye Olde Inn, second floor (green slimes, AKA Slime Inn)"},
	{"AR1115", "Generic potions store"},
	{"AR1116", "Generic weapons store"},
	{"AR1117", "Generic potions store"},
	{"AR1200", "S Baldur's Gate (docks, Iron Throne, Low Lantern, Umberlee temple)"},
	{"AR1201", "Generic home, ground floor (ogre mages)"},
	{"AR1202", "Generic home, second floor"},
	{"AR1203", "Generic home, ground floor"},
	{"AR1204", "Generic home, second floor"},
	{"AR1205", "Generic home, ground floor"},
	{"AR1206", "Generic home, second floor"},
	{"AR1207", "Warehouse (loose basilisk)"},
	{"AR1208", "Warehouse (Noralee)"},
	{"AR1209", "Generic home, ground floor (Larriaz the Sirine)"},
	{"AR1210", "Generic home, second floor"},
	{"AR1211", "Ghorak's home, ground floor"},
	{"AR1212", "Ghorak's home, second floor"},
	{"AR1213", "Cordyr's home, ground floor"},
	{"AR1214", "Cordyr's home, second floor"},
	{"AR1215", "Jopalin's Tavern"},
	{"AR1300", "SE Baldur's Gate (Blade and Stars)"},
	{"AR1301", "Warehouse"},
	{"AR1302", "Well-Adjusted Al's General Store"},
	{"AR1303", "Warehouse (Nadarin)"},
	{"AR1304", "Generic home, ground floor"},
	{"AR1305", "Generic home, second floor"},
	{"AR1306", "Generic inn, ground floor (Euric)"},
	{"AR1307", "Generic inn, second floor (Sanadal Gwist)"},
	{"AR1308", "Generic home, ground floor"},
	{"AR1309", "Generic home, second floor"},
	{"AR1310", "Generic home, ground floor"},
	{"AR1311", "Generic home, second floor"},
	{"AR1312", "Gantolandan's home, ground floor"},
	{"AR1313", "Gantolandan's home, second floor"},
	{"AR1314", "Generic home, ground floor"},
	{"AR1315", "Generic home, second floor"},
	{"AR1316", "Generic home, ground floor (thieves Taxek and Michael)"},
	{"AR1317", "Generic home, second floor"},
	{"AR1320", "Generic store"},
	{"AR1400", "Fishing village (Ajantis, farmer Brun, Gerde, lots of ankhegs)"},
	{"AR1401", "Ankheg pit"},
	{"AR1402", "Fisherman's home"},
	{"AR1403", "Fisherman's home"},
	{"AR1404", "Brun's home"},
	{"AR1500", "Balduran's Isle, north (AKA Werewolf Isle)"},
	{"AR1501", "Balduran's ship, ground floor"},
	{"AR1502", "Balduran's ship, second floor"},
	{"AR1503", "Balduran's ship, third floor"},
	{"AR1504", "Balduran's ship, fourth floor (Karoug)"},
	{"AR1505", "Dradeel's home"},
	{"AR1600", "Cloakwood, third main area (shadow druids, Eldoth, Faldorn)"},
	{"AR1601", "Tree house, ground floor"},
	{"AR1602", "Tree house, second floor (Amarande)"},
	{"AR1603", "Baby wyvern cave (Peter of the North)"},
	{"AR1700", "Cloakwood, fourth main area (wyverns)"},
	{"AR1800", "Cloakwood mines, exterior"},
	{"AR1801", "Cloakwood mines, first subterranean level (river plug)"},
	{"AR1802", "Cloakwood mines, third subterranean level (Natasha, ogre mage)"},
	{"AR1803", "Cloakwood mines, fourth subterranean level (Davaeorn, Stephan)"},
	{"AR1804", "Cloakwood mines, second subterranean level (Yeslick, Hareishan)"},
	{"AR1805", "Cloakwood mines, barracks ground floor"},
	{"AR1806", "Cloakwood mines, barracks second floor"},
	{"AR1807", "Cloakwood mines, elevator"},
	{"AR1808", "Cloakwood mines, storehouse"},
	{"AR1809", "Cloakwood mines, shed leading to elevator"},
	{"AR1900", "Bandit Camp"},
	{"AR1901", "Bandit Camp, main tent (Raemon, Venkt, Hakt, Britik)"},
	{"AR1902", "Bandit Camp, tent (Ardenor Crush)"},
	{"AR1903", "Bandit Camp, cave (Garclax)"},
	{"AR1904", "Bandit Camp, tent (Tersus)"},
	{"AR1905", "Bandit Camp, tent (Knott)"},
	{"AR1906", "Bandit Camp, tent"},
	{"AR1907", "Bandit Camp, tent (Taugosz Khosann)"},
	{"AR2000", "Balduran's Isle, south (AKA Werewolf Isle, Delainy/Durlyle)"},
	{"AR2001", "Generic hut"},
	{"AR2002", "Main hut (Kaishas Gan, Tailas)"},
	{"AR2003", "Generic hut"},
	{"AR2004", "Generic hut"},
	{"AR2005", "Generic hut"},
	{"AR2006", "Generic hut"},
	{"AR2007", "Taloun's hut"},
	{"AR2008", "Generic hut"},
	{"AR2009", "Generic hut"},
	{"AR2010", "Generic hut"},
	{"AR2011", "Generic hut"},
	{"AR2012", "Werewolf caverns"},
	{"AR2100", "Cloakwood, second main area (spider nest, Centeol)"},
	{"AR2101", "Spider nest (Centeol)"},
	{"AR2200", "Cloakwood, first main area (Aldeth Sashenstar, Seniyad, Coran)"},
	{"AR2215", "Hunting lodge"},
	{"AR2300", "Friendly Arm Inn, exterior"},
	{"AR2301", "Friendly Arm Inn, ground floor (Bentley Mirrorshade, Khalid, Jaheira)"},
	{"AR2302", "Friendly Arm Inn, second floor (Unshey)"},
	{"AR2303", "Friendly Arm Inn, third floor (Landrin, Golden Pantaloons)"},
	{"AR2304", "Friendly Arm Inn, Temple of Wisdom (Gellana Mirrorshade)"},
	{"AR2305", "Friendly Arm Inn, generic home"},
	{"AR2306", "Friendly Arm Inn, Joia's home"},
	{"AR2400", "Peldvale (Viconia, Raiken)"},
	{"AR2600", "Candlekeep (prologue), exterior"},
	{"AR2602", "Candlekeep (prologue), Priest's Quarters (Shank)"},
	{"AR2605", "Candlekeep (prologue), infirmary"},
	{"AR2606", "Candlekeep (prologue), storehouse"},
	{"AR2607", "Candlekeep (prologue), bunkhouse (Carbos)"},
	{"AR2608", "Candlekeep Citadel, ground floor (Karan)"},
	{"AR2609", "Candlekeep Citadel, second floor (Koveras)"},
	{"AR2610", "Candlekeep Citadel, third floor (Rieltar, Brunos Costak, Tuth and Kestor)"},
	{"AR2611", "Candlekeep Citadel, fourth floor (Shistal)"},
	{"AR2612", "Candlekeep Citadel, fifth floor (Gorion's old room)"},
	{"AR2613", "Candlekeep Catacombs, entrance area"},
	{"AR2614", "Candlekeep Citadel, sixth floor (Ulraunt, Tethtoril)"},
	{"AR2615", "Candlekeep Catacombs, first level"},
	{"AR2616", "Candlekeep (prologue), Inn ground floor"},
	{"AR2617", "Candlekeep (prologue), Inn second floor"},
	{"AR2618", "Candlekeep (prologue), barracks"},
	{"AR2619", "Candlekeep Catacombs, second level"},
	{"AR2626", "Candlekeep (chapter 6), exterior"},
	{"AR2627", "Candlekeep (chapter 6), Priest's Quarters"},
	{"AR2628", "Candlekeep (chapter 6), storehouse"},
	{"AR2629", "Candlekeep (chapter 6), Inn ground floor"},
	{"AR2630", "Candlekeep (chapter 6), Inn second floor"},
	{"AR2631", "Candlekeep (chapter 6), barracks"},
	{"AR2632", "Candlekeep (chapter 6), bunkhouse"},
	{"AR2633", "Candlekeep (chapter 6), infirmary"},
	{"AR2643", "Candlekeep (prologue), warehouse (Obe's party combat training)"},
	{"AR2700", "Lion's Way (E of Candlekeep, Gorion's ambush, Imoen, Xzar, Montaron)"},
	{"AR2800", "Coast Way (S of Friendly Arm Inn, destroyed caravan)"},
	{"AR2900", "Larswood (Teven, Osmadi, Corsone)"},
	{"AR3000", "Spider Wood (E of Larswood, Thayvian Red Wizards)"},
	{"AR3100", "Shipwreck's Coast (S of Candlekeep, Shoal, Droth, Mad Arcand, Surgeon)"},
	{"AR3200", "High Hedge, exterior (Kivan)"},
	{"AR3201", "High Hedge, generic house"},
	{"AR3202", "High Hedge, interior (Thalantyr)"},
	{"AR3300", "Beregost (Garrick, Jovial Juggler, Feldepost's Inn, Burning Wizard, Red Sheaf))"},
	{"AR3301", "Thunderhammer Smithy (Taerom Fuiruim)"},
	{"AR3302", "Generic home"},
	{"AR3303", "Red Sheaf, second floor"},
	{"AR3304", "Jovial Juggler, ground floor (Bjornin, Gurke)"},
	{"AR3305", "Jovial Juggler, second floor front (Oogie)"},
	{"AR3306", "Jovial Juggler, second floor rear"},
	{"AR3307", "Burning Wizard, ground floor (Zhurlong)"},
	{"AR3308", "Burning Wizard, second floor"},
	{"AR3309", "Generic home, ground floor"},
	{"AR3310", "Generic home, second floor"},
	{"AR3311", "Generic home, ground floor"},
	{"AR3312", "Generic home, second floor"},
	{"AR3313", "Mirianne's home, ground floor"},
	{"AR3314", "Mirianne's home, second floor"},
	{"AR3315", "Landrin's home (spiders)"},
	{"AR3316", "Generic home"},
	{"AR3317", "Borland's home"},
	{"AR3318", "Generic home"},
	{"AR3319", "Galteran's home"},
	{"AR3320", "Travenhurst Manor, ground floor"},
	{"AR3321", "Travenhurst Manor, second floor"},
	{"AR3322", "Travenhurst Manor, Servants' Quarters"},
	{"AR3323", "Generic home, ground floor"},
	{"AR3324", "Generic home, second floor"},
	{"AR3325", "Generic home, second floor"},
	{"AR3326", "Generic home, ground floor"},
	{"AR3327", "Generic home, ground floor"},
	{"AR3328", "Generic home, second floor"},
	{"AR3329", "Generic home, second floor"},
	{"AR3330", "Generic home, ground floor"},
	{"AR3331", "Generic home, ground floor (Colquatle)"},
	{"AR3332", "Generic home, second floor"},
	{"AR3333", "Firebeard Elvenhair's home, ground floor"},
	{"AR3334", "Firebeard Elvenhair's home, second floor"},
	{"AR3335", "Generic home, ground floor"},
	{"AR3336", "Generic home, second floor"},
	{"AR3337", "Generic home, second floor"},
	{"AR3338", "Generic home, ground floor"},
	{"AR3339", "Generic home, ground floor"},
	{"AR3340", "Generic home, second floor"},
	{"AR3341", "Generic home, ground floor"},
	{"AR3342", "Generic home, second floor"},
	{"AR3343", "Generic home"},
	{"AR3344", "Generic home"},
	{"AR3345", "Generic home, ground floor"},
	{"AR3346", "Generic home, second floor"},
	{"AR3347", "Generic home, ground floor"},
	{"AR3348", "Generic home, second floor"},
	{"AR3349", "Generic home, ground floor"},
	{"AR3350", "Generic home, second floor"},
	{"AR3351", "Feldepost's Inn, ground floor (Marl)"},
	{"AR3352", "Feldepost's Inn, second floor (Algernon)"},
	{"AR3353", "Generic store (Kagain)"},
	{"AR3354", "Generic home"},
	{"AR3355", "Generic home, ground floor"},
	{"AR3356", "Generic home, second floor"},
	{"AR3357", "Red Sheaf, ground floor (Perdue)"},
	{"AR3400", "Beregost Temple, exterior (Cattack)"},
	{"AR3401", "Beregost Temple, vestibule"},
	{"AR3402", "Beregost Temple, interior (AKA Song of the Morning, Keldath Ormlyr)"},
	{"AR3500", "Mutamin's Garden (Shar-Teel, Mutamin, Korax, basilisks, Tamah)"},
	{"AR3600", "Seawatcher - Lighthouse (Safana, Ardrouine, Sil)"},
	{"AR3601", "Black Alaric's cave (flesh golems)"},
	{"AR3700", "Red Canyons (Bassilus, Melicamp)"},
	{"AR3800", "South Beregost Road"},
	{"AR3802", "Generic cave"},
	{"AR3900", "Ulcaster School, exterior (Ulcaster, Icharyd)"},
	{"AR3901", "Ulcaster School, dungeon"},
	{"AR4000", "Gullykin, exterior"},
	{"AR4001", "Jenkal's home, ground floor"},
	{"AR4002", "Jenkal's home, second floor"},
	{"AR4003", "Temple of Yondalla, ground floor"},
	{"AR4004", "Temple of Yondalla, basement"},
	{"AR4005", "Generic home, ground floor"},
	{"AR4006", "Generic home, basement"},
	{"AR4007", "Generic home, ground floor"},
	{"AR4008", "Generic home, basement"},
	{"AR4009", "Generic home, ground floor"},
	{"AR4010", "Generic home, basement"},
	{"AR4011", "Generic home, ground floor"},
	{"AR4012", "Generic home, basement"},
	{"AR4013", "Generic home, ground floor"},
	{"AR4014", "Generic home, basement"},
	{"AR4100", "Archaeological Site, exterior (Brage, Charleston Nib, Doomsayer)"},
	{"AR4101", "Archaeological Site, interior tomb"},
	{"AR4200", "Fisherman's Lake (Drizzt. Bjornin's half-ogres)"},
	{"AR4300", "North Nashkel Road (N of Nashkel)"},
	{"AR4400", "Lonely Peaks (Hulrik and Arabelle, Sarhedra, Arghain)"},
	{"AR4401", "Generic cave (ettercaps)"},
	{"AR4500", "Firewine Bridge (Kahrk, Carsa, Poe, Bentan, Melium)"},
	{"AR4501", "Wyvern cave"},
	{"AR4600", "Bear River (N of Gnoll Stronghold, Larel, Nevill, Jared)"},
	{"AR4700", "Xvart Village (Nexlit, Ursa, Borda)"},
	{"AR4701", "Generic cave (cave bear)"},
	{"AR4800", "Nashkel (Minsc, Edwin, Berrun Ghastkill, Belching Dragon, Temple of Helm)"},
	{"AR4801", "Nashkel Inn"},
	{"AR4802", "Temple of Helm (Nalin)"},
	{"AR4803", "Nashkel Store"},
	{"AR4804", "Nashkel Manor, ground floor"},
	{"AR4805", "Nashkel Manor, second floor (Samantha)"},
	{"AR4806", "Joseph's home"},
	{"AR4807", "Generic farmhouse"},
	{"AR4808", "Generic home"},
	{"AR4809", "Belching Dragon Tavern (Volo)"},
	{"AR4810", "Nashkel barracks"},
	{"AR4900", "Nashkel Carnival (Branwen, Great Gazib)"},
	{"AR4901", "Small carnival tent (armor merchant)"},
	{"AR4902", "Small carnival tent (black lotus)"},
	{"AR4903", "Large carnival tent (Vitiare)"},
	{"AR4904", "Large carnival tent (gambling)"},
	{"AR4905", "Small carnival tent (rare potions merchant)"},
	{"AR4906", "Small carnival tent (Zordral and Bentha)"},
	{"AR4907", "Small carnival tent (magic items merchant)"},
	{"AR4908", "Small carnival tent (melee weapons merchant)"},
	{"AR4909", "Small carnival tent (ranged weapons merchant)"},
	{"AR5000", "Valley of the Tombs (Nashkel mines exit, Narcillicus, Hentold)"},
	{"AR5001", "Tombs"},
	{"AR5100", "Gnoll Stronghold (Dynaheir)"},
	{"AR5101", "Generic cave (xvarts)"},
	{"AR5102", "Generic cave (Tome of Leadership and Influence)"},
	{"AR5103", "Generic cave (cariron crawlers)"},
	{"AR5200", "Dryad Falls (Cloudpeak Dryad, Drienne, Ingot, Krumm, Caldo)"},
	{"AR5201", "Firewine Ruins (Lendarn, ogre mage, undead knights)"},
	{"AR5202", "Generic cave"},
	{"AR5300", "Fire Leaf Forest (S of Nashkel, Albert, Rufie, Vax, Sendai)"},
	{"AR5400", "Nashkel Mines, exterior (Prism)"},
	{"AR5401", "Nashkel Mines, first subterranean level (Dink)"},
	{"AR5402", "Nashkel Mines, second subterranean level (Kylee, Beldin)"},
	{"AR5403", "Nashkel Mines, third subterranean level (Joseph)"},
	{"AR5404", "Nashkel Mines, fourth subterranean level"},
	{"AR5405", "Nashkel Mines, Mulahey's lair (Xan, Mulahey)"},
	{"AR5406", "Mine storehouse"},
	{"AR5500", "Gibberling Mountains (Samuel, Hafiz)"},
	{"AR5506", "Candlekeep Caves (Diarmid, Prat, Sakul, Tam, Bor)"},
	{"AR5600", "Random encounter area"},
	{"AR5601", "Random encounter area"},
	{"AR5700", "Random encounter area"},
	{"AR5701", "Random encounter area"},
	{"AR5800", "Random encounter area"},
	{"AR5801", "Random encounter area"},
	{"AR5900", "Random encounter area"},
	{"AR5901", "Random encounter area"},
	{"AR6000", "Random encounter area"},
	{"AR6001", "Random encounter area"},
	{"AR6100", "Random encounter area"},
	{"OH1000", "Dorn - Random Encounter Area"},
	{"OH2000", "Neera - Adoy's Enclave, exterior"},
	{"OH2010", "Neera - Adoy's Enclave, interior"},
	{"OH3000", "Rasaad - Dark Moon temple, exterior"},
	{"OH3010", "Rasaad - Dark Moon temple, interior"},
	{"OH3020", "Rasaad - Dark Moon temple, interior"},
	{"OH3100", "Rasaad - Dark Moon temple, interior"},
}
cheatAreasArena = {
	{"OH9310", "The Black Pits: Arena 1"},
	{"OH9350", "The Black Pits: Arena 2"},
	{"OH9360", "The Black Pits: Hub"},
}
cheatAreasTutorial = {
	{"TU0015", "Baldur's Gate Estate (Tutorial starts here)"},
	{"TU0016", "Baldur's Gate Estate (Tutorial area)"},
	{"TU0017", "Baldur's Gate Estate (Tutorial area)"},
	{"TU0018", "Baldur's Gate Estate Cellar (Tutorial area)"}
}

fontcolors = {}
-- AABBGGRR
fontcolors['1'] = 'FFCAE2E9' -- title
fontcolors['2'] = 'FFCAE2E9' -- title highlight
fontcolors['3'] = 'FFCAE2E9' -- subtitle
fontcolors['4'] = 'FFEEFFFF' -- subtitle highlight
fontcolors['5'] = 'FF000000' -- parchment
fontcolors['6'] = 'FFEEFFFF' -- parchment highlight
fontcolors['7'] = 'FF000000' -- alternate parchment
fontcolors['8'] = 'FF102526' -- alternate parchment highlight
fontcolors['9'] = 'FFCDD6D9' -- semitrans dark background
fontcolors['A'] = 'FFFDE6E9' -- semitrans dark background highlight
fontcolors['B'] = 'FFCECECE'
fontcolors['C'] = 'FFC8F0C8' -- Minty update color
fontcolors['D'] = 'FF96C8FF' -- orangy subtitle color
fontcolors['E'] = 'FF808080' -- fake the unclickable colour
fontcolors['R'] = 'FF0000FF' -- red
fontcolors['G'] = 'FF00FF00' -- green
fontcolors['M'] = 'FF000080' -- parchment red
fontcolors['$'] = 'FF82E6FF' -- gold yellow/orange

characters = {}

tempStats = {}

styles =
{
	gamelog =
	{
		color = 'B',
		font = 'POSTANTI',
		point = 12,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},
	normal =
	{
		color = 'B',
		font = 'NORMAL',
		point = 12,
		valign = 'top',
		halign = 'left',
    useFontZoom = 1,
	},
	rg_trajan =
	{
		color = 'B',
		font = 'RGTRAJ',
		point = 16,
		useFontZoom = 1,
		valign = 'top',
		halign = 'left',
	},
	normal_parchment =
	{
		color = '5',
		font = 'NORMAL',
		point = 12,
		valign = 'top',
		halign = 'left',
    useFontZoom = 1,
	},
	title =
	{
		color = '1',
		font = 'REALMS',
		point = 16,
		valign = 'center',
		halign = 'center',
    useFontZoom = 0,
	},
	parchment = 
	{
		color = '5',
		font = 'NORMAL' ,
		point = 12,
		valign = 'top',
		halign = 'left',
    useFontZoom = 1,
	},
	button =
	{
		color = 'B',
		font = 'STONESML' ,
		point = 10,
		valign = 'center',
		halign = 'center',
		upper = 1,
		pad = {8,8,8,8},
    useFontZoom = 0,
	},
	button_parchment =
	{
		color = '5',
		font = 'MODESTOM',
		point = 12,
		valign = 'center',
		halign = 'center',
		pad = {0,5,0,0},
    useFontZoom = 0,
	},
	label =
	{
		color = 'B',
		font = 'STONESML',
		point = 12,
		valign = 'center',
		halign = 'center',
    useFontZoom = 0,
	},
	label_parchment =
	{
		color = '5',
		font = 'STONESML',
		point = 12,
		valign = 'center',
		halign = 'center',
    useFontZoom = 0,
	},
	edit =
	{
		color = 'B',
		font = 'NORMAL',
		point = 12,
		valign = 'top',
		halign = 'left',
    useFontZoom = 1,
	},
	edit_parchment =
	{
		color = '5',
		font = 'NORMAL',
		point = 12,
		valign = 'top',
		halign = 'left',
    useFontZoom = 1,
	},
	list =
	{
		color = 'B',
		font = 'STONESML',
		point = 12,
		valign = 'center',
		halign = 'left',
    useFontZoom = 0,
	},
	list_parchment =
	{
		color = '5',
		font = 'STONESML',
		point = 12,
		valign = 'center',
		halign = 'left',
    useFontZoom = 0,
	},
	gold =
	{
		color = '$',
		font = 'NORMAL',
		point = 12,
		valign = 'center',
		halign = 'center',
    useFontZoom = 0,
	}
}

chapterBackgrounds = {}
chapterBackgrounds[0] = "GUICHP0B"
chapterBackgrounds[1] = "GUICHP1B"
chapterBackgrounds[2] = "GUICHP2B"
chapterBackgrounds[3] = "GUICHP3B"
chapterBackgrounds[4] = "GUICHP4B"
chapterBackgrounds[5] = "GUICHP5B"
chapterBackgrounds[6] = "GUICHP6B"
chapterBackgrounds[7] = "GUICHP7B"
chapterBackgrounds[8] = "GUICHP8B"
chapterBackgrounds[9] = "GUICHP9B"
chapterBackgrounds[10] = "GUICHP10B"
chapterBackgrounds[11] = "GUICHP11B"
chapterBackgrounds[12] = "GUICHP12B"
chapterBackgrounds[13] = "GUICHP13B"
chapterBackgrounds[14] = "GUICHP0A"
chapterBackgrounds[15] = "GUICHP0A"
chapterBackgrounds[16] = "GUICHP0A"
chapterBackgrounds[17] = "GUICHP0A"
chapterBackgrounds[18] = "GUICHP0A"
chapterBackgrounds[19] = "GUICHP0A"
chapterBackgrounds[20] = "BPEND"
chapterBackgrounds[21] = "GUICHP0A"
chapterBackgrounds[22] = "GUICHP0A"
chapterBackgrounds[23] = "GUICHP0A"
chapterBackgrounds[24] = "GUICHP0A"
chapterBackgrounds[25] = "GUICHP0A"
chapterBackgrounds[26] = "GUICHP0A"
chapterBackgrounds[27] = "GUICHP0A"
chapterBackgrounds[28] = "GUICHP0A"
chapterBackgrounds[29] = "GUICHP0A"
chapterBackgrounds[30] = "GUICHP0A"
chapterBackgrounds[31] = "GUICHP0A"
chapterBackgrounds[32] = "GUICHP0A"
chapterBackgrounds[33] = "GUICHP0A"
chapterBackgrounds[34] = "GUICHP0A"
chapterBackgrounds[35] = "GUICHP0A"
chapterBackgrounds[36] = "GUICHP0A"
chapterBackgrounds[37] = "GUICHP0A"
chapterBackgrounds[38] = "GUICHP0A"
chapterBackgrounds[39] = "GUICHP0A"
chapterBackgrounds[40] = "GUICHP0A"
chapterBackgrounds[41] = "GUICHP0A"
chapterBackgrounds[42] = "GUICHP0A"
chapterBackgrounds[43] = "GUICHP0A"
chapterBackgrounds[44] = "GUICHP0A"
chapterBackgrounds[45] = "GUICHP0A"
chapterBackgrounds[46] = "GUICHP0A"
chapterBackgrounds[47] = "GUICHP0A"
chapterBackgrounds[48] = "GUICHP0A"
chapterBackgrounds[49] = "GUICHP0A"
chapterBackgrounds[50] = "GUICHP0A"
chapterBackgrounds[51] = "GUICHP0A"
chapterBackgrounds[52] = "GUIDRM2"
chapterBackgrounds[53] = "GUIDRM3"
chapterBackgrounds[54] = "GUIDRM4"
chapterBackgrounds[55] = "GUIDRM5"
chapterBackgrounds[56] = "GUIDRM6"
chapterBackgrounds[57] = "GUIDRM7"
chapterBackgrounds[58] = "ARRIVE"
chapterBackgrounds[59] = "LEAVE"

chapterBackgrounds[100] = "GUICHP6B"

const =
{
	ENTRY_TYPE_NONE = -1,
	ENTRY_TYPE_USER = 0,
	ENTRY_TYPE_INPROGRESS = 1,
	ENTRY_TYPE_COMPLETE = 2,
	ENTRY_TYPE_INFO = 4,
	
	ENTRIES_IDX_STRREF = 1,
	ENTRIES_IDX_QUEST = 2,
	ENTRIES_IDX_STATE = 3,
	ENTRIES_IDX_SUBGROUP = 4,
	ENTRIES_IDX_TIMESTAMP = 5,
	ENTRIES_IDX_RECV = 6,
	
	JOURNAL_STATE_USER  = 0,
	JOURNAL_STATE_INPROGRESS = 1,
	JOURNAL_STATE_COMPLETE = 2,
	JOURNAL_STATE_INFO = 4,
	
	QUEST_IDX_ID = 1,
	QUEST_IDX_STRREF = 3,
	QUEST_IDX_STATE = 5,
	QUEST_IDX_CHAPTER = 6,
	QUEST_IDX_RECV = 7,
	
	USER_IDX_STRREF = 1,
	USER_IDX_TIMESTAMP = 2,
	USER_IDX_STATE = 3,
	USER_IDX_CHAPTER = 4,
	USER_IDX_RECV = 5,
	
	INFO_IDX_STRREF = 1,
	INFO_IDX_TIMESTAMP = 2,
	INFO_IDX_STATE = 3,
	INFO_IDX_CHAPTER = 4,
	INFO_IDX_RECV = 5,
	
	IDX_IMPORTANT = 1,
		
	STEP_DUALCLASS_CLASS = 24,
	STEP_DUALCLASS_PROFICIENCIES = 25,
	STEP_DUALCLASS_DONE = 27,
	
	CUSTOMIZE_ID = 17,
	SCRIPT_ID = 11,
	EXPORT_ID = 13,
	SOUND_ID = 20,
		
	JOURNAL_MODE_QUESTS = 1,
	JOURNAL_MODE_JOURNAL = 2,
	JOURNAL_MODE_EDIT = 3,
}
function buildQuestsTable()
	Infinity_Log("Initializing Quests")
	quests = {}
	userNotes = {}
	subGroups = {}
	looseEntries = {}
	createQuest    ( 31270 )
	createEntry    ( 31270, -1, 31438, {}, nil )
	createEntry    ( 31270, -1, 31439, {}, nil )
	createEntry    ( 31270, -1, 31440, {}, nil )
	createEntry    ( 31270, -1, 31441, {}, nil )
	createEntry    ( 31270, -1, 31442, {}, nil )
	createEntry    ( 31270, -1, 31443, {}, nil )
	createEntry    ( 31270, -1, 31444, {}, nil )
	createEntry    ( 31270, -1, 31445, {}, nil )
	createEntry    ( 31270, -1, 31446, {}, nil )
	createEntry    ( 31270, -1, 31447, {}, nil )
	createEntry    ( 31270, -1, 31448, {}, nil )
	createEntry    ( 31270, -1, 31449, {}, nil )
	createEntry    ( 31270, -1, 31450, {}, nil )
	createEntry    ( 31270, -1, 31451, {}, nil )
	createEntry    ( 31270, -1, 31452, {}, nil )
	createEntry    ( 31270, -1, 31453, {}, nil )
	createEntry    ( 31270, -1, 31454, {}, nil )
	createEntry    ( 31270, -1, 31455, {}, nil )
	createEntry    ( 31270, -1, 31456, {}, nil )
	createEntry    ( 31270, -1, 31457, {}, nil )
	createEntry    ( 31270, -1, 31458, {}, nil )
	createEntry    ( 31270, -1, 31459, {}, nil )
	createEntry    ( 31270, -1, 31460, {}, nil )
	createEntry    ( 31270, -1, 31461, {}, nil )
	createEntry    ( 31270, -1, 31462, {}, nil )
	createEntry    ( 31270, -1, 31463, {}, nil )
	createEntry    ( 31270, -1, 31464, {}, nil )
	createEntry    ( 31270, -1, 31465, {}, nil )
	createEntry    ( 31270, -1, 31466, {}, nil )
	createEntry    ( 31270, -1, 31467, {}, nil )
	createEntry    ( 31270, -1, 31468, {}, nil )
	createEntry    ( 31270, -1, 31469, {}, nil )
	createEntry    ( 31270, -1, 31470, {}, nil )
	createEntry    ( 31270, -1, 31471, {}, nil )
	createEntry    ( 31270, -1, 31472, {}, nil )
	createEntry    ( 31270, -1, 31473, {}, nil )
	createEntry    ( 31270, -1, 31474, {}, nil )
	createEntry    ( 31270, -1, 31475, {}, nil )
	createEntry    ( 31270, -1, 32134, {}, nil )
	createQuest    ( 31271 )
	createEntry    ( 31271, -1, 27415, {}, nil )
	createEntry    ( 31271, -1, 27416, {}, nil )
	createQuest    ( 31272 )
	createEntry    ( 31272, -1, 27082, {}, nil )
	createEntry    ( 31272, -1, 27083, {}, nil )
	createQuest    ( 31273 )
	createEntry    ( 31273, -1, 26851, {}, nil )
	createEntry    ( 31273, -1, 26852, {}, nil )
	createQuest    ( 31274 )
	createEntry    ( 31274, -1, 27334, {}, nil )
	createEntry    ( 31274, -1, 27335, {}, nil )
	createEntry    ( 31274, -1, 27336, {}, nil )
	createEntry    ( 31274, -1, 27337, {}, nil )
	createEntry    ( 31274, -1, 27338, {}, nil )
	createQuest    ( 31275 )
	createEntry    ( 31275, -1, 26853, {}, nil )
	createEntry    ( 31275, -1, 26854, {}, nil )
	createQuest    ( 31276 )
	createEntry    ( 31276, -1, 26954, {}, nil )
	createEntry    ( 31276, -1, 26955, {}, nil )
	createEntry    ( 31276, -1, 26956, {}, nil )
	createEntry    ( 31276, -1, 26957, {}, nil )
	createQuest    ( 31277 )
	createEntry    ( 31277, -1, 27499, {}, nil )
	createQuest    ( 31279 )
	createEntry    ( 31279, -1, 26829, {}, nil )
	createEntry    ( 31279, -1, 27046, {}, nil )
	createEntry    ( 31279, -1, 27047, {}, nil )
	createEntry    ( 31279, -1, 27059, {}, nil )
	createEntry    ( 31279, -1, 27060, {}, nil )
	createEntry    ( 31279, -1, 27172, {}, nil )
	createEntry    ( 31279, -1, 27173, {}, nil )
	createEntry    ( 31279, -1, 27270, {}, nil )
	createEntry    ( 31279, -1, 27455, {}, nil )
	createQuest    ( 31280 )
	createEntry    ( 31280, -1, 27470, {}, nil )
	createQuest    ( 31281 )
	createEntry    ( 31281, -1, 27451, {}, nil )
	createEntry    ( 31281, -1, 32158, {}, nil )
	createEntry    ( 31281, -1, 27454, {}, nil )
	createQuest    ( 31282 )
	createEntry    ( 31282, -1, 27500, {}, nil )
	createQuest    ( 31283 )
	createEntry    ( 31283, -1, 30177, {}, nil )
	createQuest    ( 31284 )
	createEntry    ( 31284, -1, 27079, {}, nil )
	createEntry    ( 31284, -1, 32877, {}, nil )
	createQuest    ( 31285 )
	createEntry    ( 31285, -1, 27497, {}, nil )
	createQuest    ( 31286 )
	createEntry    ( 31286, -1, 26980, {}, nil )
	createEntry    ( 31286, -1, 26981, {}, nil )
	createEntry    ( 31286, -1, 26983, {}, nil )
	createEntry    ( 31286, -1, 26985, {}, nil )
	createQuest    ( 31287 )
	createEntry    ( 31287, -1, 27106, {}, nil )
	createEntry    ( 31287, -1, 27164, {}, nil )
	createEntry    ( 31287, -1, 27165, {}, nil )
	createQuest    ( 31288 )
	createEntry    ( 31288, -1, 26841, {}, nil )
	createEntry    ( 31288, -1, 26842, {}, nil )
	createEntry    ( 31288, -1, 26843, {}, nil )
	createEntry    ( 31288, -1, 26844, {}, nil )
	createEntry    ( 31288, -1, 26845, {}, nil )
	createEntry    ( 31288, -1, 26846, {}, nil )
	createEntry    ( 31288, -1, 26847, {}, nil )
	createEntry    ( 31288, -1, 27317, {}, nil )
	createEntry    ( 31288, -1, 32175, {}, nil )
	createQuest    ( 31289 )
	createEntry    ( 31289, -1, 26813, {}, nil )
	createEntry    ( 31289, -1, 26814, {}, nil )
	createEntry    ( 31289, -1, 26815, {}, nil )
	createEntry    ( 31289, -1, 27315, {}, nil )
	createEntry    ( 31289, -1, 27413, {}, nil )
	createEntry    ( 31289, -1, 27414, {}, nil )
	createQuest    ( 31290 )
	createEntry    ( 31290, -1, 26816, {}, nil )
	createEntry    ( 31290, -1, 26817, {}, nil )
	createEntry    ( 31290, -1, 26818, {}, nil )
	createEntry    ( 31290, -1, 26819, {}, nil )
	createQuest    ( 31291 )
	createEntry    ( 31291, -1, 26820, {}, nil )
	createEntry    ( 31291, -1, 26821, {}, nil )
	createEntry    ( 31291, -1, 27430, {}, nil )
	createEntry    ( 31291, -1, 32835, {}, nil )
	createQuest    ( 31292 )
	createEntry    ( 31292, -1, 27360, {}, nil )
	createEntry    ( 31292, -1, 27361, {}, nil )
	createQuest    ( 31293 )
	createEntry    ( 31293, -1, 27450, {}, nil )
	createEntry    ( 31293, -1, 27451, {}, nil )
	createEntry    ( 31293, -1, 32158, {}, nil )
	createEntry    ( 31293, -1, 27452, {}, nil )
	createEntry    ( 31293, -1, 27453, {}, nil )
	createQuest    ( 31294 )
	createEntry    ( 31294, -1, 27076, {}, nil )
	createEntry    ( 31294, -1, 27077, {}, nil )
	createEntry    ( 31294, -1, 27078, {}, nil )
	createEntry    ( 31294, -1, 27125, {}, nil )
	createEntry    ( 31294, -1, 27126, {}, nil )
	createQuest    ( 31295 )
	createEntry    ( 31295, -1, 26848, {}, nil )
	createEntry    ( 31295, -1, 26849, {}, nil )
	createQuest    ( 31296 )
	createEntry    ( 31296, -1, 27320, {}, nil )
	createEntry    ( 31296, -1, 27321, {}, nil )
	createEntry    ( 31296, -1, 27343, {}, nil )
	createQuest    ( 31297 )
	createEntry    ( 31297, -1, 27318, {}, nil )
	createEntry    ( 31297, -1, 27319, {}, nil )
	createEntry    ( 31297, -1, 27322, {}, nil )
	createQuest    ( 31298 )
	createEntry    ( 31298, -1, 27027, {}, nil )
	createEntry    ( 31298, -1, 27028, {}, nil )
	createEntry    ( 31298, -1, 27108, {}, nil )
	createEntry    ( 31298, -1, 27294, {}, nil )
	createQuest    ( 31299 )
	createEntry    ( 31299, -1, 27299, {}, nil )
	createEntry    ( 31299, -1, 27300, {}, nil )
	createQuest    ( 31300 )
	createEntry    ( 31300, -1, 26865, {}, nil )
	createEntry    ( 31300, -1, 26866, {}, nil )
	createEntry    ( 31300, -1, 27090, {}, nil )
	createEntry    ( 31300, -1, 27097, {}, nil )
	createEntry    ( 31300, -1, 27203, {}, nil )
	createEntry    ( 31300, -1, 27204, {}, nil )
	createEntry    ( 31300, -1, 27205, {}, nil )
	createEntry    ( 31300, -1, 27206, {}, nil )
	createQuest    ( 31301 )
	createEntry    ( 31301, -1, 27498, {}, nil )
	createQuest    ( 31304 )
	createEntry    ( 31304, -1, 26898, {}, nil )
	createEntry    ( 31304, -1, 26902, {}, nil )
	createQuest    ( 31305 )
	createEntry    ( 31305, -1, 26909, {}, nil )
	createQuest    ( 31306 )
	createEntry    ( 31306, -1, 27405, {}, nil )
	createEntry    ( 31306, -1, 27489, {}, nil )
	createEntry    ( 31306, -1, 27490, {}, nil )
	createEntry    ( 31306, -1, 27491, {}, nil )
	createQuest    ( 31307 )
	createEntry    ( 31307, -1, 26919, {}, nil )
	createEntry    ( 31307, -1, 26920, {}, nil )
	createQuest    ( 31308 )
	createEntry    ( 31308, -1, 26928, {}, nil )
	createQuest    ( 31309 )
	createEntry    ( 31309, -1, 26936, {}, nil )
	createEntry    ( 31309, -1, 26937, {}, nil )
	createEntry    ( 31309, -1, 26938, {}, nil )
	createEntry    ( 31309, -1, 26939, {}, nil )
	createEntry    ( 31309, -1, 26944, {}, nil )
	createEntry    ( 31309, -1, 26945, {}, nil )
	createEntry    ( 31309, -1, 26946, {}, nil )
	createQuest    ( 31310 )
	createEntry    ( 31310, -1, 26987, {}, nil )
	createEntry    ( 31310, -1, 24077, {}, nil )
	createEntry    ( 31310, -1, 26988, {}, nil )
	createEntry    ( 31310, -1, 26990, {}, nil )
	createQuest    ( 31311 )
	createEntry    ( 31311, -1, 26992, {}, nil )
	createEntry    ( 31311, -1, 26993, {}, nil )
	createQuest    ( 31312 )
	createEntry    ( 31312, -1, 26994, {}, nil )
	createEntry    ( 31312, -1, 26995, {}, nil )
	createEntry    ( 31312, -1, 26996, {}, nil )
	createEntry    ( 31312, -1, 26997, {}, nil )
	createQuest    ( 31313 )
	createEntry    ( 31313, -1, 27005, {}, nil )
	createEntry    ( 31313, -1, 27006, {}, nil )
	createEntry    ( 31313, -1, 27007, {}, nil )
	createEntry    ( 31313, -1, 32338, {}, nil )
	createQuest    ( 31314 )
	createEntry    ( 31314, -1, 26959, {}, nil )
	createEntry    ( 31314, -1, 26963, {}, nil )
	createEntry    ( 31314, -1, 26984, {}, nil )
	createEntry    ( 31314, -1, 27137, {}, nil )
	createEntry    ( 31314, -1, 27138, {}, nil )
	createEntry    ( 31314, -1, 27139, {}, nil )
	createEntry    ( 31314, -1, 27140, {}, nil )
	createEntry    ( 31314, -1, 27141, {}, nil )
	createEntry    ( 31314, -1, 27142, {}, nil )
	createEntry    ( 31314, -1, 27143, {}, nil )
	createEntry    ( 31314, -1, 27144, {}, nil )
	createEntry    ( 31314, -1, 27145, {}, nil )
	createEntry    ( 31314, -1, 27146, {}, nil )
	createQuest    ( 31315 )
	createEntry    ( 31315, -1, 26868, {}, nil )
	createEntry    ( 31315, -1, 26914, {}, nil )
	createEntry    ( 31315, -1, 26915, {}, nil )
	createEntry    ( 31315, -1, 26916, {}, nil )
	createEntry    ( 31315, -1, 26917, {}, nil )
	createEntry    ( 31315, -1, 26930, {}, nil )
	createEntry    ( 31315, -1, 27009, {}, nil )
	createEntry    ( 31315, -1, 27011, {}, nil )
	createEntry    ( 31315, -1, 27026, {}, nil )
	createEntry    ( 31315, -1, 27075, {}, nil )
	createEntry    ( 31315, -1, 27166, {}, nil )
	createEntry    ( 31315, -1, 27167, {}, nil )
	createEntry    ( 31315, -1, 27168, {}, nil )
	createEntry    ( 31315, -1, 27169, {}, nil )
	createEntry    ( 31315, -1, 27170, {}, nil )
	createQuest    ( 31316 )
	createEntry    ( 31316, -1, 27012, {}, nil )
	createEntry    ( 31316, -1, 27013, {}, nil )
	createEntry    ( 31316, -1, 27014, {}, nil )
	createEntry    ( 31316, -1, 27015, {}, nil )
	createEntry    ( 31316, -1, 27016, {}, nil )
	createEntry    ( 31316, -1, 27017, {}, nil )
	createEntry    ( 31316, -1, 27018, {}, nil )
	createQuest    ( 31317 )
	createEntry    ( 31317, -1, 27031, {}, nil )
	createEntry    ( 31317, -1, 27032, {}, nil )
	createEntry    ( 31317, -1, 27033, {}, nil )
	createEntry    ( 31317, -1, 27034, {}, nil )
	createEntry    ( 31317, -1, 27521, {}, nil )
	createQuest    ( 31318 )
	createEntry    ( 31318, -1, 27035, {}, nil )
	createEntry    ( 31318, -1, 27036, {}, nil )
	createEntry    ( 31318, -1, 27435, {}, nil )
	createQuest    ( 31319 )
	createEntry    ( 31319, -1, 27193, {}, nil )
	createEntry    ( 31319, -1, 27194, {}, nil )
	createQuest    ( 31320 )
	createEntry    ( 31320, -1, 23521, {}, nil )
	createEntry    ( 31320, -1, 27054, {}, nil )
	createEntry    ( 31320, -1, 27055, {}, nil )
	createQuest    ( 31321 )
	createEntry    ( 31321, -1, 27056, {}, nil )
	createEntry    ( 31321, -1, 27057, {}, nil )
	createEntry    ( 31321, -1, 27058, {}, nil )
	createQuest    ( 31322 )
	createEntry    ( 31322, -1, 27061, {}, nil )
	createQuest    ( 31323 )
	createEntry    ( 31323, -1, 27065, {}, nil )
	createEntry    ( 31323, -1, 27066, {}, nil )
	createEntry    ( 31323, -1, 27068, {}, nil )
	createEntry    ( 31323, -1, 27069, {}, nil )
	createQuest    ( 31324 )
	createEntry    ( 31324, -1, 27070, {}, nil )
	createEntry    ( 31324, -1, 27071, {}, nil )
	createQuest    ( 31325 )
	createEntry    ( 31325, -1, 27074, {}, nil )
	createQuest    ( 31326 )
	createEntry    ( 31326, -1, 27114, {}, nil )
	createQuest    ( 31327 )
	createEntry    ( 31327, -1, 21268, {}, nil )
	createEntry    ( 31327, -1, 26929, {}, nil )
	createEntry    ( 31327, -1, 27172, {}, nil )
	createEntry    ( 31327, -1, 27267, {}, nil )
	createEntry    ( 31327, -1, 27268, {}, nil )
	createEntry    ( 31327, -1, 27269, {}, nil )
	createEntry    ( 31327, -1, 27270, {}, nil )
	createEntry    ( 31327, -1, 27436, {}, nil )
	createEntry    ( 31327, -1, 31453, {}, nil )
	createQuest    ( 31328 )
	createEntry    ( 31328, -1, 26947, {}, nil )
	createEntry    ( 31328, -1, 26948, {}, nil )
	createEntry    ( 31328, -1, 26949, {}, nil )
	createEntry    ( 31328, -1, 26950, {}, nil )
	createQuest    ( 31329 )
	createEntry    ( 31329, -1, 27019, {}, nil )
	createEntry    ( 31329, -1, 27020, {}, nil )
	createEntry    ( 31329, -1, 27021, {}, nil )
	createEntry    ( 31329, -1, 27022, {}, nil )
	createQuest    ( 31330 )
	createEntry    ( 31330, -1, 27121, {}, nil )
	createEntry    ( 31330, -1, 27122, {}, nil )
	createQuest    ( 31331 )
	createEntry    ( 31331, -1, 27113, {}, nil )
	createQuest    ( 31332 )
	createEntry    ( 31332, -1, 27112, {}, nil )
	createQuest    ( 31333 )
	createEntry    ( 31333, -1, 27120, {}, nil )
	createQuest    ( 31334 )
	createEntry    ( 31334, -1, 27130, {}, nil )
	createQuest    ( 31335 )
	createEntry    ( 31335, -1, 27128, {}, nil )
	createEntry    ( 31335, -1, 27129, {}, nil )
	createEntry    ( 31335, -1, 27130, {}, nil )
	createQuest    ( 31336 )
	createEntry    ( 31336, -1, 27213, {}, nil )
	createEntry    ( 31336, -1, 27216, {}, nil )
	createQuest    ( 31337 )
	createEntry    ( 31337, -1, 27067, {}, nil )
	createQuest    ( 31338 )
	createEntry    ( 31338, -1, 27475, {}, nil )
	createQuest    ( 31339 )
	createEntry    ( 31339, -1, 27133, {}, nil )
	createEntry    ( 31339, -1, 27134, {}, nil )
	createEntry    ( 31339, -1, 27135, {}, nil )
	createQuest    ( 31340 )
	createEntry    ( 31340, -1, 26883, {}, nil )
	createEntry    ( 31340, -1, 26884, {}, nil )
	createQuest    ( 31341 )
	createEntry    ( 31341, -1, 27153, {}, nil )
	createQuest    ( 31342 )
	createEntry    ( 31342, -1, 26927, {}, nil )
	createEntry    ( 31342, -1, 26958, {}, nil )
	createEntry    ( 31342, -1, 26965, {}, nil )
	createEntry    ( 31342, -1, 26991, {}, nil )
	createEntry    ( 31342, -1, 27045, {}, nil )
	createEntry    ( 31342, -1, 27136, {}, nil )
	createEntry    ( 31342, -1, 27147, {}, nil )
	createEntry    ( 31342, -1, 27157, {}, nil )
	createEntry    ( 31342, -1, 27158, {}, nil )
	createEntry    ( 31342, -1, 27159, {}, nil )
	createEntry    ( 31342, -1, 27160, {}, nil )
	createEntry    ( 31342, -1, 27161, {}, nil )
	createEntry    ( 31342, -1, 27174, {}, nil )
	createEntry    ( 31342, -1, 27175, {}, nil )
	createEntry    ( 31342, -1, 27176, {}, nil )
	createEntry    ( 31342, -1, 27328, {}, nil )
	createEntry    ( 31342, -1, 27389, {}, nil )
	createEntry    ( 31342, -1, 27393, {}, nil )
	createEntry    ( 31342, -1, 27479, {}, nil )
	createEntry    ( 31342, -1, 27494, {}, nil )
	createQuest    ( 31343 )
	createEntry    ( 31343, -1, 26822, {}, nil )
	createEntry    ( 31343, -1, 26823, {}, nil )
	createEntry    ( 31343, -1, 26824, {}, nil )
	createEntry    ( 31343, -1, 26825, {}, nil )
	createEntry    ( 31343, -1, 26826, {}, nil )
	createEntry    ( 31343, -1, 26827, {}, nil )
	createEntry    ( 31343, -1, 26828, {}, nil )
	createQuest    ( 31344 )
	createEntry    ( 31344, -1, 26839, {}, nil )
	createEntry    ( 31344, -1, 26840, {}, nil )
	createEntry    ( 31344, -1, 26885, {}, nil )
	createEntry    ( 31344, -1, 26886, {}, nil )
	createEntry    ( 31344, -1, 26921, {}, nil )
	createEntry    ( 31344, -1, 26922, {}, nil )
	createEntry    ( 31344, -1, 26978, {}, nil )
	createEntry    ( 31344, -1, 27041, {}, nil )
	createEntry    ( 31344, -1, 27042, {}, nil )
	createEntry    ( 31344, -1, 27043, {}, nil )
	createEntry    ( 31344, -1, 27044, {}, nil )
	createEntry    ( 31344, -1, 27271, {}, nil )
	createEntry    ( 31344, -1, 27272, {}, nil )
	createEntry    ( 31344, -1, 27273, {}, nil )
	createEntry    ( 31344, -1, 27296, {}, nil )
	createQuest    ( 31345 )
	createEntry    ( 31345, -1, 27182, {}, nil )
	createQuest    ( 31346 )
	createEntry    ( 31346, -1, 27184, {}, nil )
	createEntry    ( 31346, -1, 27185, {}, nil )
	createQuest    ( 31347 )
	createEntry    ( 31347, -1, 27188, {}, nil )
	createEntry    ( 31347, -1, 27189, {}, nil )
	createQuest    ( 31348 )
	createEntry    ( 31348, -1, 27221, {}, nil )
	createEntry    ( 31348, -1, 27222, {}, nil )
	createQuest    ( 31349 )
	createEntry    ( 31349, -1, 27101, {}, nil )
	createEntry    ( 31349, -1, 27102, {}, nil )
	createQuest    ( 31350 )
	createEntry    ( 31350, -1, 27194, {}, nil )
	createQuest    ( 31351 )
	createEntry    ( 31351, -1, 27202, {}, nil )
	createQuest    ( 31352 )
	createEntry    ( 31352, -1, 27127, {}, nil )
	createEntry    ( 31352, -1, 27225, {}, nil )
	createEntry    ( 31352, -1, 27226, {}, nil )
	createEntry    ( 31352, -1, 27227, {}, nil )
	createQuest    ( 31355 )
	createEntry    ( 31355, -1, 27231, {}, nil )
	createEntry    ( 31355, -1, 27232, {}, nil )
	createEntry    ( 31355, -1, 27233, {}, nil )
	createEntry    ( 31355, -1, 27234, {}, nil )
	createEntry    ( 31355, -1, 27235, {}, nil )
	createEntry    ( 31355, -1, 27236, {}, nil )
	createEntry    ( 31355, -1, 32757, {}, nil )
	createQuest    ( 31357 )
	createEntry    ( 31357, -1, 26893, {}, nil )
	createEntry    ( 31357, -1, 26894, {}, nil )
	createEntry    ( 31357, -1, 26895, {}, nil )
	createEntry    ( 31357, -1, 26896, {}, nil )
	createQuest    ( 31358 )
	createEntry    ( 31358, -1, 27211, {}, nil )
	createQuest    ( 31359 )
	createEntry    ( 31359, -1, 27249, {}, nil )
	createEntry    ( 31359, -1, 27250, {}, nil )
	createEntry    ( 31359, -1, 27251, {}, nil )
	createQuest    ( 31360 )
	createEntry    ( 31360, -1, 26793, {}, nil )
	createEntry    ( 31360, -1, 26982, {}, nil )
	createEntry    ( 31360, -1, 27183, {}, nil )
	createEntry    ( 31360, -1, 27240, {}, nil )
	createEntry    ( 31360, -1, 27241, {}, nil )
	createEntry    ( 31360, -1, 27242, {}, nil )
	createEntry    ( 31360, -1, 27243, {}, nil )
	createEntry    ( 31360, -1, 27253, {}, nil )
	createEntry    ( 31360, -1, 31188, {}, nil )
	createQuest    ( 31361 )
	createEntry    ( 31361, -1, 27258, {}, nil )
	createQuest    ( 31362 )
	createEntry    ( 31362, -1, 27256, {}, nil )
	createEntry    ( 31362, -1, 27257, {}, nil )
	createQuest    ( 31363 )
	createEntry    ( 31363, -1, 27477, {}, nil )
	createEntry    ( 31363, -1, 27478, {}, nil )
	createQuest    ( 31364 )
	createEntry    ( 31364, -1, 27276, {}, nil )
	createEntry    ( 31364, -1, 27278, {}, nil )
	createQuest    ( 31365 )
	createEntry    ( 31365, -1, 27277, {}, nil )
	createQuest    ( 31366 )
	createEntry    ( 31366, -1, 27428, {}, nil )
	createEntry    ( 31366, -1, 27429, {}, nil )
	createQuest    ( 31367 )
	createEntry    ( 31367, -1, 27084, {}, nil )
	createQuest    ( 31368 )
	createEntry    ( 31368, -1, 27051, {}, nil )
	createEntry    ( 31368, -1, 27301, {}, nil )
	createEntry    ( 31368, -1, 27302, {}, nil )
	createQuest    ( 31369 )
	createEntry    ( 31369, -1, 27307, {}, nil )
	createEntry    ( 31369, -1, 27308, {}, nil )
	createEntry    ( 31369, -1, 27309, {}, nil )
	createEntry    ( 31369, -1, 27310, {}, nil )
	createEntry    ( 31369, -1, 27311, {}, nil )
	createEntry    ( 31369, -1, 27312, {}, nil )
	createEntry    ( 31369, -1, 27313, {}, nil )
	createEntry    ( 31369, -1, 27314, {}, nil )
	createEntry    ( 31369, -1, 27316, {}, nil )
	createQuest    ( 31370 )
	createEntry    ( 31370, -1, 27323, {}, nil )
	createEntry    ( 31370, -1, 27324, {}, nil )
	createQuest    ( 31371 )
	createEntry    ( 31371, -1, 27341, {}, nil )
	createEntry    ( 31371, -1, 27342, {}, nil )
	createQuest    ( 31372 )
	createEntry    ( 31372, -1, 26913, {}, nil )
	createQuest    ( 31373 )
	createEntry    ( 31373, -1, 27419, {}, nil )
	createEntry    ( 31373, -1, 27420, {}, nil )
	createQuest    ( 31374 )
	createEntry    ( 31374, -1, 26925, {}, nil )
	createQuest    ( 31375 )
	createEntry    ( 31375, -1, 27344, {}, nil )
	createEntry    ( 31375, -1, 27345, {}, nil )
	createQuest    ( 31376 )
	createEntry    ( 31376, -1, 27349, {}, nil )
	createEntry    ( 31376, -1, 27350, {}, nil )
	createQuest    ( 31377 )
	createEntry    ( 31377, -1, 27347, {}, nil )
	createQuest    ( 31378 )
	createEntry    ( 31378, -1, 27354, {}, nil )
	createEntry    ( 31378, -1, 27355, {}, nil )
	createEntry    ( 31378, -1, 27356, {}, nil )
	createQuest    ( 31379 )
	createEntry    ( 31379, -1, 26879, {}, nil )
	createEntry    ( 31379, -1, 26880, {}, nil )
	createEntry    ( 31379, -1, 26881, {}, nil )
	createEntry    ( 31379, -1, 26882, {}, nil )
	createEntry    ( 31379, -1, 27358, {}, nil )
	createQuest    ( 31380 )
	createEntry    ( 31380, -1, 26870, {}, nil )
	createQuest    ( 31381 )
	createEntry    ( 31381, -1, 27362, {}, nil )
	createEntry    ( 31381, -1, 27363, {}, nil )
	createEntry    ( 31381, -1, 27364, {}, nil )
	createQuest    ( 31383 )
	createEntry    ( 31383, -1, 27104, {}, nil )
	createEntry    ( 31383, -1, 27346, {}, nil )
	createEntry    ( 31383, -1, 27348, {}, nil )
	createEntry    ( 31383, -1, 27367, {}, nil )
	createEntry    ( 31383, -1, 27368, {}, nil )
	createEntry    ( 31383, -1, 27369, {}, nil )
	createEntry    ( 31383, -1, 27372, {}, nil )
	createQuest    ( 31384 )
	createEntry    ( 31384, -1, 27171, {}, nil )
	createQuest    ( 31385 )
	createEntry    ( 31385, -1, 27376, {}, nil )
	createEntry    ( 31385, -1, 27377, {}, nil )
	createQuest    ( 31386 )
	createEntry    ( 31386, -1, 26923, {}, nil )
	createEntry    ( 31386, -1, 26924, {}, nil )
	createEntry    ( 31386, -1, 27154, {}, nil )
	createEntry    ( 31386, -1, 27155, {}, nil )
	createEntry    ( 31386, -1, 27156, {}, nil )
	createQuest    ( 31387 )
	createEntry    ( 31387, -1, 27411, {}, nil )
	createEntry    ( 31387, -1, 27412, {}, nil )
	createQuest    ( 31388 )
	createEntry    ( 31388, -1, 27029, {}, nil )
	createEntry    ( 31388, -1, 27030, {}, nil )
	createEntry    ( 31388, -1, 27274, {}, nil )
	createEntry    ( 31388, -1, 27275, {}, nil )
	createQuest    ( 31389 )
	createEntry    ( 31389, -1, 26873, {}, nil )
	createEntry    ( 31389, -1, 26874, {}, nil )
	createEntry    ( 31389, -1, 26903, {}, nil )
	createEntry    ( 31389, -1, 26910, {}, nil )
	createEntry    ( 31389, -1, 26911, {}, nil )
	createEntry    ( 31389, -1, 26969, {}, nil )
	createEntry    ( 31389, -1, 26970, {}, nil )
	createEntry    ( 31389, -1, 26971, {}, nil )
	createEntry    ( 31389, -1, 26972, {}, nil )
	createEntry    ( 31389, -1, 26973, {}, nil )
	createEntry    ( 31389, -1, 26974, {}, nil )
	createEntry    ( 31389, -1, 26975, {}, nil )
	createEntry    ( 31389, -1, 26976, {}, nil )
	createEntry    ( 31389, -1, 26977, {}, nil )
	createQuest    ( 31390 )
	createEntry    ( 31390, -1, 26811, {}, nil )
	createEntry    ( 31390, -1, 27092, {}, nil )
	createEntry    ( 31390, -1, 27148, {}, nil )
	createEntry    ( 31390, -1, 27187, {}, nil )
	createEntry    ( 31390, -1, 27219, {}, nil )
	createEntry    ( 31390, -1, 27220, {}, nil )
	createEntry    ( 31390, -1, 27282, {}, nil )
	createEntry    ( 31390, -1, 27290, {}, nil )
	createEntry    ( 31390, -1, 27386, {}, nil )
	createEntry    ( 31390, -1, 27388, {}, nil )
	createEntry    ( 31390, -1, 27390, {}, nil )
	createEntry    ( 31390, -1, 27391, {}, nil )
	createEntry    ( 31390, -1, 27392, {}, nil )
	createEntry    ( 31390, -1, 27394, {}, nil )
	createEntry    ( 31390, -1, 27408, {}, nil )
	createEntry    ( 31390, -1, 27409, {}, nil )
	createQuest    ( 31391 )
	createEntry    ( 31391, -1, 27086, {}, nil )
	createEntry    ( 31391, -1, 27123, {}, nil )
	createEntry    ( 31391, -1, 27124, {}, nil )
	createQuest    ( 31392 )
	createEntry    ( 31392, -1, 27421, {}, nil )
	createQuest    ( 31393 )
	createEntry    ( 31393, -1, 27424, {}, nil )
	createQuest    ( 31394 )
	createEntry    ( 31394, -1, 27177, {}, nil )
	createEntry    ( 31394, -1, 27178, {}, nil )
	createEntry    ( 31394, -1, 27179, {}, nil )
	createQuest    ( 31395 )
	createEntry    ( 31395, -1, 27247, {}, nil )
	createEntry    ( 31395, -1, 27248, {}, nil )
	createQuest    ( 31396 )
	createEntry    ( 31396, -1, 26960, {}, nil )
	createEntry    ( 31396, -1, 27162, {}, nil )
	createEntry    ( 31396, -1, 27163, {}, nil )
	createQuest    ( 31397 )
	createEntry    ( 31397, -1, 27486, {}, nil )
	createEntry    ( 31397, -1, 27487, {}, nil )
	createQuest    ( 31398 )
	createEntry    ( 31398, -1, 27458, {}, nil )
	createEntry    ( 31398, -1, 27459, {}, nil )
	createEntry    ( 31398, -1, 27460, {}, nil )
	createQuest    ( 31399 )
	createEntry    ( 31399, -1, 27461, {}, nil )
	createEntry    ( 31399, -1, 27462, {}, nil )
	createEntry    ( 31399, -1, 27463, {}, nil )
	createEntry    ( 31399, -1, 27464, {}, nil )
	createEntry    ( 31399, -1, 27465, {}, nil )
	createEntry    ( 31399, -1, 27466, {}, nil )
	createQuest    ( 31400 )
	createEntry    ( 31400, -1, 26872, {}, nil )
	createEntry    ( 31400, -1, 27505, {}, nil )
	createEntry    ( 31400, -1, 27513, {}, nil )
	createEntry    ( 31400, -1, 20597, {}, nil )
	createQuest    ( 31401 )
	createEntry    ( 31401, -1, 26850, {}, nil )
	createEntry    ( 31401, -1, 26856, {}, nil )
	createEntry    ( 31401, -1, 26857, {}, nil )
	createEntry    ( 31401, -1, 26859, {}, nil )
	createEntry    ( 31401, -1, 26860, {}, nil )
	createEntry    ( 31401, -1, 26861, {}, nil )
	createEntry    ( 31401, -1, 26862, {}, nil )
	createEntry    ( 31401, -1, 27217, {}, nil ) --
	createEntry    ( 31401, -1, 27218, {}, nil ) --
	createEntry    ( 31401, -1, 27378, {}, nil )
	createEntry    ( 31401, -1, 27379, {}, nil )
	createEntry    ( 31401, -1, 27380, {}, nil ) --
	createEntry    ( 31401, -1, 27381, {}, nil ) --
	createEntry    ( 31401, -1, 27382, {}, nil ) --
	createEntry    ( 31401, -1, 27383, {}, nil ) --
	createEntry    ( 31401, -1, 27468, {}, nil )
	createEntry    ( 31401, -1, 27469, {}, nil ) --
	createEntry    ( 31401, -1, 27473, {}, nil )
	createEntry    ( 31401, -1, 27474, {}, nil )
	createEntry    ( 31401, -1, 27476, {}, nil )
	createEntry    ( 31401, -1, 27492, {}, nil ) --
	createEntry    ( 31401, -1, 26858, {}, nil ) --
	createQuest    ( 31402 )
	createEntry    ( 31402, -1, 27374, {}, nil )
	createEntry    ( 31402, -1, 27375, {}, nil )
	createQuest    ( 31403 )
	createEntry    ( 31403, -1, 27115, {}, nil )
	createEntry    ( 31403, -1, 27116, {}, nil )
	createEntry    ( 31403, -1, 27117, {}, nil )
	createEntry    ( 31403, -1, 27118, {}, nil )
	createEntry    ( 31403, -1, 27119, {}, nil )
	createQuest    ( 31404 )
	createEntry    ( 31404, -1, 27431, {}, nil )
	createEntry    ( 31404, -1, 27432, {}, nil )
	createQuest    ( 31405 )
	createEntry    ( 31405, -1, 26931, {}, nil )
	createEntry    ( 31405, -1, 26932, {}, nil )
	createEntry    ( 31405, -1, 26933, {}, nil )
	createEntry    ( 31405, -1, 26934, {}, nil )
	createQuest    ( 31406 )
	createEntry    ( 31406, -1, 27517, {}, nil )
	createQuest    ( 31407 )
	createEntry    ( 31407, -1, 27288, {}, nil )
	createQuest    ( 31408 )
	createEntry    ( 31408, -1, 26986, {}, nil )
	createEntry    ( 31408, -1, 27008, {}, nil )
	createEntry    ( 31408, -1, 27186, {}, nil )
	createEntry    ( 31408, -1, 27397, {}, nil )
	createEntry    ( 31408, -1, 27422, {}, nil )
	createEntry    ( 31408, -1, 27423, {}, nil )
	createEntry    ( 31408, -1, 27425, {}, nil )
	createEntry    ( 31408, -1, 27426, {}, nil )
	createEntry    ( 31408, -1, 27427, {}, nil )
	createQuest    ( 31409 )
	createEntry    ( 31409, -1, 8058, {}, nil )
	createEntry    ( 31409, -1, 27279, {}, nil )
	createQuest    ( 31410 )
	createEntry    ( 31410, -1, 26806, {}, nil )
	createEntry    ( 31410, -1, 26807, {}, nil )
	createEntry    ( 31410, -1, 26808, {}, nil )
	createEntry    ( 31410, -1, 26809, {}, nil )
	createEntry    ( 31410, -1, 26810, {}, nil )
	createEntry    ( 31410, -1, 27384, {}, nil )
	createEntry    ( 31410, -1, 27385, {}, nil )
	createQuest    ( 31411 )
	createEntry    ( 31411, -1, 27439, {}, nil )
	createEntry    ( 31411, -1, 27440, {}, nil )
	createEntry    ( 31411, -1, 27441, {}, nil )
	createEntry    ( 31411, -1, 27442, {}, nil )
	createEntry    ( 31411, -1, 27443, {}, nil )
	createEntry    ( 31411, -1, 27444, {}, nil )
	createEntry    ( 31411, -1, 27445, {}, nil )
	createEntry    ( 31411, -1, 27446, {}, nil )
	createEntry    ( 31411, -1, 27447, {}, nil )
	createEntry    ( 31411, -1, 27448, {}, nil )
	createEntry    ( 31411, -1, 27471, {}, nil )
	createEntry    ( 31411, -1, 27472, {}, nil )
	createQuest    ( 31412 )
	createEntry    ( 31412, -1, 26855, {}, nil )
	createEntry    ( 31412, -1, 27073, {}, nil )
	createEntry    ( 31412, -1, 27244, {}, nil )
	createEntry    ( 31412, -1, 27245, {}, nil )
	createEntry    ( 31412, -1, 27246, {}, nil )
	createQuest    ( 31413 )
	createEntry    ( 31413, -1, 27237, {}, nil )
	createEntry    ( 31413, -1, 27238, {}, nil )
	createEntry    ( 31413, -1, 27239, {}, nil )
	createQuest    ( 31414 )
	createEntry    ( 31414, -1, 26935, {}, nil )
	createEntry    ( 31414, -1, 26940, {}, nil )
	createEntry    ( 31414, -1, 26941, {}, nil )
	createEntry    ( 31414, -1, 26942, {}, nil )
	createEntry    ( 31414, -1, 26943, {}, nil )
	createEntry    ( 31414, -1, 26951, {}, nil )
	createEntry    ( 31414, -1, 26952, {}, nil )
	createEntry    ( 31414, -1, 26953, {}, nil )
	createEntry    ( 31414, -1, 27023, {}, nil )
	createEntry    ( 31414, -1, 27024, {}, nil )
	createEntry    ( 31414, -1, 27025, {}, nil )
	createEntry    ( 31414, -1, 27052, {}, nil )
	createEntry    ( 31414, -1, 27053, {}, nil )
	createEntry    ( 31414, -1, 27072, {}, nil )
	createEntry    ( 31414, -1, 27191, {}, nil )
	createEntry    ( 31414, -1, 27195, {}, nil )
	createEntry    ( 31414, -1, 27196, {}, nil )
	createEntry    ( 31414, -1, 27197, {}, nil )
	createEntry    ( 31414, -1, 27198, {}, nil )
	createEntry    ( 31414, -1, 27199, {}, nil )
	createEntry    ( 31414, -1, 27200, {}, nil )
	createEntry    ( 31414, -1, 27228, {}, nil )
	createEntry    ( 31414, -1, 27229, {}, nil )
	createEntry    ( 31414, -1, 27230, {}, nil )
	createEntry    ( 31414, -1, 27252, {}, nil )
	createEntry    ( 31414, -1, 27265, {}, nil )
	createEntry    ( 31414, -1, 27266, {}, nil )
	createEntry    ( 31414, -1, 27438, {}, nil )
	createEntry    ( 31414, -1, 27456, {}, nil )
	createEntry    ( 31414, -1, 27457, {}, nil )
	createQuest    ( 31415 )
	createEntry    ( 31415, -1, 26908, {}, nil )
	createEntry    ( 31415, -1, 27107, {}, nil )
	createEntry    ( 31415, -1, 27259, {}, nil )
	createEntry    ( 31415, -1, 27260, {}, nil )
	createEntry    ( 31415, -1, 27261, {}, nil )
	createEntry    ( 31415, -1, 27262, {}, nil )
	createEntry    ( 31415, -1, 27263, {}, nil )
	createEntry    ( 31415, -1, 27293, {}, nil )
	createEntry    ( 31415, -1, 27295, {}, nil )
	createQuest    ( 31416 )
	createEntry    ( 31416, -1, 26812, {}, nil )
	createEntry    ( 31416, -1, 26871, {}, nil )
	createEntry    ( 31416, -1, 26892, {}, nil )
	createEntry    ( 31416, -1, 26962, {}, nil )
	createEntry    ( 31416, -1, 26967, {}, nil )
	createEntry    ( 31416, -1, 27091, {}, nil )
	createEntry    ( 31416, -1, 27093, {}, nil )
	createEntry    ( 31416, -1, 27094, {}, nil )
	createEntry    ( 31416, -1, 27095, {}, nil )
	createEntry    ( 31416, -1, 27096, {}, nil )
	createEntry    ( 31416, -1, 27132, {}, nil )
	createEntry    ( 31416, -1, 27190, {}, nil )
	createEntry    ( 31416, -1, 27192, {}, nil )
	createEntry    ( 31416, -1, 27201, {}, nil )
	createEntry    ( 31416, -1, 27283, {}, nil )
	createEntry    ( 31416, -1, 27284, {}, nil )
	createEntry    ( 31416, -1, 27285, {}, nil )
	createEntry    ( 31416, -1, 27286, {}, nil )
	createEntry    ( 31416, -1, 27287, {}, nil )
	createEntry    ( 31416, -1, 27327, {}, nil )
	createEntry    ( 31416, -1, 27329, {}, nil )
	createEntry    ( 31416, -1, 27330, {}, nil )
	createEntry    ( 31416, -1, 27331, {}, nil )
	createEntry    ( 31416, -1, 27332, {}, nil )
	createEntry    ( 31416, -1, 27333, {}, nil )
	createEntry    ( 31416, -1, 27339, {}, nil )
	createEntry    ( 31416, -1, 27340, {}, nil )
	createEntry    ( 31416, -1, 27352, {}, nil )
	createEntry    ( 31416, -1, 27387, {}, nil )
	createEntry    ( 31416, -1, 27399, {}, nil )
	createEntry    ( 31416, -1, 27488, {}, nil )
	createEntry    ( 31416, -1, 27514, {}, nil )
	createQuest    ( 31417 )
	createEntry    ( 31417, -1, 26966, {}, nil )
	createEntry    ( 31417, -1, 27207, {}, nil )
	createEntry    ( 31417, -1, 27208, {}, nil )
	createEntry    ( 31417, -1, 27209, {}, nil )
	createEntry    ( 31417, -1, 27210, {}, nil )
	createQuest    ( 31418 )
	createEntry    ( 31418, -1, 26830, {}, nil )
	createEntry    ( 31418, -1, 26831, {}, nil )
	createEntry    ( 31418, -1, 26832, {}, nil )
	createEntry    ( 31418, -1, 26833, {}, nil )
	createEntry    ( 31418, -1, 26834, {}, nil )
	createEntry    ( 31418, -1, 26838, {}, nil )
	createEntry    ( 31418, -1, 26887, {}, nil )
	createEntry    ( 31418, -1, 26888, {}, nil )
	createEntry    ( 31418, -1, 27105, {}, nil )
	createEntry    ( 31418, -1, 27292, {}, nil )
	createEntry    ( 31418, -1, 27303, {}, nil )
	createEntry    ( 31418, -1, 27304, {}, nil )
	createEntry    ( 31418, -1, 27507, {}, nil )
	createEntry    ( 31418, -1, 27305, {}, nil )
	createQuest    ( 31419 )
	createEntry    ( 31419, -1, 26867, {}, nil )
	createEntry    ( 31419, -1, 27481, {}, nil )
	createEntry    ( 31419, -1, 23508, {}, nil )
	createEntry    ( 31419, -1, 27483, {}, nil )
	createEntry    ( 31419, -1, 27484, {}, nil )
	createQuest    ( 31420 )
	createEntry    ( 31420, -1, 27495, {}, nil )
	createQuest    ( 31421 )
	createEntry    ( 31421, -1, 1827, {}, nil )
	createEntry    ( 31421, -1, 27493, {}, nil )
	createEntry    ( 31421, -1, 27503, {}, nil )
	createEntry    ( 31421, -1, 27504, {}, nil )
	createEntry    ( 31421, -1, 6332, {}, nil )
	createEntry    ( 31421, -1, 6354, {}, nil )
	createEntry    ( 31421, -1, 6355, {}, nil )
	createEntry    ( 31421, -1, 6356, {}, nil )
	-- createQuest    ( 31422 ) -- All moved to journal.
	--createEntry    ( 31422, -1, 26835, {}, nil )
	--createEntry    ( 31422, -1, 26836, {}, nil )
	--createEntry    ( 31422, -1, 26863, {}, nil )
	--createEntry    ( 31422, -1, 26864, {}, nil )
	--createEntry    ( 31422, -1, 26869, {}, nil )
	--createEntry    ( 31422, -1, 26875, {}, nil )
	--createEntry    ( 31422, -1, 26876, {}, nil )
	--createEntry    ( 31422, -1, 26877, {}, nil ) -- main quest from Berrun Ghastkill
	--createEntry    ( 31422, -1, 26878, {}, nil ) -- main quest from Berrun Ghastkill
	--createEntry    ( 31422, -1, 26912, {}, nil )
	--createEntry    ( 31422, -1, 26999, {}, nil ) -- Drizzt
	--createEntry    ( 31422, -1, 27000, {}, nil ) -- Drizzt
	--createEntry    ( 31422, -1, 27001, {}, nil ) -- Drizzt
	--createEntry    ( 31422, -1, 27098, {}, nil )
	--createEntry    ( 31422, -1, 27099, {}, nil )
	--createEntry    ( 31422, -1, 27100, {}, nil )
	--createEntry    ( 31422, -1, 27103, {}, nil )
	--createEntry    ( 31422, -1, 27264, {}, nil )
	--createEntry    ( 31422, -1, 27280, {}, nil )
	--createEntry    ( 31422, -1, 27281, {}, nil )
	--createEntry    ( 31422, -1, 27289, {}, nil )
	--createEntry    ( 31422, -1, 27291, {}, nil )
	--createEntry    ( 31422, -1, 27297, {}, nil ) -- unused
	--createEntry    ( 31422, -1, 27298, {}, nil ) -- unused
	--createEntry    ( 31422, -1, 27395, {}, nil )
	--createEntry    ( 31422, -1, 27396, {}, nil )
	--createEntry    ( 31422, -1, 27400, {}, nil )
	--createEntry    ( 31422, -1, 27401, {}, nil )
	--createEntry    ( 31422, -1, 27402, {}, nil )
	--createEntry    ( 31422, -1, 27403, {}, nil )
	--createEntry    ( 31422, -1, 27404, {}, nil )
	--createEntry    ( 31422, -1, 27407, {}, nil )
	--createEntry    ( 31422, -1, 27410, {}, nil )
	--createEntry    ( 31422, -1, 27417, {}, nil )
	--createEntry    ( 31422, -1, 27506, {}, nil ) -- Volo
	--createEntry    ( 31422, -1, 32878, {}, nil ) -- unused
	createQuest    ( 31423 )
	createEntry    ( 31423, -1, 30179, {}, nil )
	createEntry    ( 31423, -1, 31698, {}, nil )
	createQuest    ( 31424 )
	createEntry    ( 31424, -1, 27496, {}, nil )
	createQuest    ( 31425 )
	createEntry    ( 31425, -1, 27501, {}, nil )
	createEntry    ( 31425, -1, 27502, {}, nil )
	createQuest    ( 31426 )
	createEntry    ( 31426, -1, 27433, {}, nil )
	createQuest    ( 31427 )
	createEntry    ( 31427, -1, 27515, {}, nil )
	createEntry    ( 31427, -1, 27516, {}, nil )
	createQuest    ( 31429 )
	createEntry    ( 31429, -1, 27518, {}, nil )
	createQuest    ( 31430 )
	createEntry    ( 31430, -1, 27519, {}, nil )
	createEntry    ( 31430, -1, 27520, {}, nil )
	createQuest    ( 31431 )
	createEntry    ( 31431, -1, 27511, {}, nil )
	createEntry    ( 31431, -1, 27512, {}, nil )
	createQuest    ( 31604 )
	createEntry    ( 31604, -1, 27149, {}, nil )
	createEntry    ( 31604, -1, 27150, {}, nil )
	createEntry    ( 31604, -1, 27151, {}, nil )
	createQuest    ( 31605 )
	createEntry    ( 31605, -1, 27109, {}, nil )
	createEntry    ( 31605, -1, 27110, {}, nil )
	createEntry    ( 31605, -1, 27111, {}, nil )
	createQuest    ( 31606 )
	createEntry    ( 31606, -1, 27080, {}, nil )
	createEntry    ( 31606, -1, 27081, {}, nil )
	createEntry    ( 31606, -1, 32885, {}, nil )
	createQuest    ( 31607 )
	createEntry    ( 31607, -1, 27085, {}, nil )
	createEntry    ( 31607, -1, 27087, {}, nil )
	createQuest    ( 31092 )
	--createEntry    ( 31092, -1, 30814, {}, nil )
	createEntry    ( 31092, -1, 30815, {}, nil )
	--createEntry    ( 31092, -1, 30816, {}, nil )
	createEntry    ( 31092, -1, 28403, {}, nil )
	createEntry    ( 31092, -1, 28427, {}, nil )
	createEntry    ( 31092, -1, 28433, {}, nil )
	createEntry    ( 31092, -1, 28458, {}, nil )
	createEntry    ( 31092, -1, 28479, {}, nil )
	createEntry    ( 31092, -1, 28503, {}, nil )
	createEntry    ( 31092, -1, 28521, {}, nil )
	createEntry    ( 31092, -1, 30818, {}, nil )
	createEntry    ( 31092, -1, 28536, {}, nil )
	createQuest    ( 28607 )
	createEntry    ( 28607, -1, 30772, {}, nil )
	createEntry    ( 28607, -1, 29023, {}, nil )
	createEntry    ( 28607, -1, 30773, {}, nil )
	createEntry    ( 28607, -1, 30774, {}, nil )
	createEntry    ( 28607, -1, 29022, {}, nil )
	createEntry    ( 28607, -1, 30775, {}, nil )
	createEntry    ( 28607, -1, 30776, {}, nil )
	createEntry    ( 28607, -1, 30777, {}, nil )
	createEntry    ( 28607, -1, 30778, {}, nil )
	createQuest    ( 27633 )
	createEntry    ( 27633, -1, 31610, {}, nil )
	createEntry    ( 27633, -1, 31611, {}, nil )
	createEntry    ( 27633, -1, 31613, {}, nil )
	createEntry    ( 27633, -1, 31618, {}, nil )
	createQuest    ( 18675 )
	createEntry    ( 18675, -1, 26979, {}, nil )
	createEntry    ( 18675, -1, 27223, {}, nil )
	createQuest    ( 31988 )
	createEntry    ( 31988, -1, 26918, {}, nil )
	createEntry    ( 31988, -1, 31969, {}, nil )
	createQuest    ( 32148 )
	createEntry    ( 32148, -1, 27212, {}, nil )
	createEntry    ( 32148, -1, 32794, {}, nil )
	createEntry    ( 32148, -1, 32893, {}, nil )
	createEntry    ( 32148, -1, 32895, {}, nil )
	createQuest    ( 32759 )
	createEntry    ( 32759, -1, 32760, {}, nil )
	createEntry    ( 32759, -1, 32795, {}, nil )
	createEntry    ( 32759, -1, 32894, {}, nil )
	createEntry    ( 32759, -1, 32896, {}, nil )	
	createQuest    ( 32202 )
	createEntry    ( 32202, -1, 32198, {}, nil )
	createEntry    ( 32202, -1, 32199, {}, nil )
	createEntry    ( 32202, -1, 32200, {}, nil )
	createQuest    ( 27561 )
	createEntry    ( 27561, -1, 27180, {}, nil )
	createEntry    ( 27561, -1, 27181, {}, nil )
	createQuest    ( 32218 )
	createEntry    ( 32218, -1, 15772, {}, nil )
	createQuest    ( 32802 )
	createEntry    ( 32802, -1, 32803, {}, nil )
	createEntry    ( 32802, -1, 32808, {}, nil )
	createEntry    ( 32802, -1, 32810, {}, nil )
	createQuest    ( 32866 )
	createEntry    ( 32866, -1, 27418, {}, nil )
end
